/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IGraduationOracle,
  IGraduationOracleInterface,
} from "../../../contracts/LaunchCampaign.sol/IGraduationOracle";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "usdAmount",
        type: "uint256",
      },
    ],
    name: "nativeTargetForUsd",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IGraduationOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IGraduationOracleInterface {
    return new Interface(_abi) as IGraduationOracleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IGraduationOracle {
    return new Contract(address, _abi, runner) as unknown as IGraduationOracle;
  }
}
