/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ILaunchFactoryGraduationNotify,
  ILaunchFactoryGraduationNotifyInterface,
} from "../../../contracts/LaunchCampaign.sol/ILaunchFactoryGraduationNotify";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "creator",
        type: "address",
      },
      {
        internalType: "address",
        name: "lpToken",
        type: "address",
      },
    ],
    name: "notifyCampaignGraduated",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ILaunchFactoryGraduationNotify__factory {
  static readonly abi = _abi;
  static createInterface(): ILaunchFactoryGraduationNotifyInterface {
    return new Interface(_abi) as ILaunchFactoryGraduationNotifyInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ILaunchFactoryGraduationNotify {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ILaunchFactoryGraduationNotify;
  }
}
