/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPhase1TreasuryRouter,
  IPhase1TreasuryRouterInterface,
} from "../../../contracts/LaunchCampaign.sol/IPhase1TreasuryRouter";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint8",
        name: "kind",
        type: "uint8",
      },
      {
        internalType: "uint8",
        name: "profile",
        type: "uint8",
      },
    ],
    name: "route",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IPhase1TreasuryRouter__factory {
  static readonly abi = _abi;
  static createInterface(): IPhase1TreasuryRouterInterface {
    return new Interface(_abi) as IPhase1TreasuryRouterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPhase1TreasuryRouter {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IPhase1TreasuryRouter;
  }
}
