/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRiskRegistryView,
  IRiskRegistryViewInterface,
} from "../../../contracts/LaunchCampaign.sol/IRiskRegistryView";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "wallet",
        type: "address",
      },
    ],
    name: "assertWalletCanTrade",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IRiskRegistryView__factory {
  static readonly abi = _abi;
  static createInterface(): IRiskRegistryViewInterface {
    return new Interface(_abi) as IRiskRegistryViewInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRiskRegistryView {
    return new Contract(address, _abi, runner) as unknown as IRiskRegistryView;
  }
}
