/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace CreatorRegistry {
  export type CreatorProfileStruct = {
    tier: BigNumberish;
    trustScore: BigNumberish;
    liveBondingCount: BigNumberish;
    lastLaunchTimestamp: BigNumberish;
    restricted: boolean;
    manualReviewRequired: boolean;
  };

  export type CreatorProfileStructOutput = [
    tier: bigint,
    trustScore: bigint,
    liveBondingCount: bigint,
    lastLaunchTimestamp: bigint,
    restricted: boolean,
    manualReviewRequired: boolean
  ] & {
    tier: bigint;
    trustScore: bigint;
    liveBondingCount: bigint;
    lastLaunchTimestamp: bigint;
    restricted: boolean;
    manualReviewRequired: boolean;
  };

  export type CreatorRulesStruct = {
    maxLiveBonding: BigNumberish;
    cooldownSeconds: BigNumberish;
    creatorBuyLockSeconds: BigNumberish;
    creatorBuyCapWei: BigNumberish;
    maxClusterWallets: BigNumberish;
  };

  export type CreatorRulesStructOutput = [
    maxLiveBonding: bigint,
    cooldownSeconds: bigint,
    creatorBuyLockSeconds: bigint,
    creatorBuyCapWei: bigint,
    maxClusterWallets: bigint
  ] & {
    maxLiveBonding: bigint;
    cooldownSeconds: bigint;
    creatorBuyLockSeconds: bigint;
    creatorBuyCapWei: bigint;
    maxClusterWallets: bigint;
  };
}

export interface CreatorRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "canLaunch"
      | "getCreatorProfile"
      | "getCreatorRules"
      | "getRulesForTier"
      | "launchRecorder"
      | "owner"
      | "recordGraduation"
      | "recordLaunch"
      | "renounceOwnership"
      | "setCreatorRestricted"
      | "setCreatorTier"
      | "setCreatorTrustScore"
      | "setLaunchRecorder"
      | "setManualReviewRequired"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CreatorGraduationRecorded"
      | "CreatorLaunchRecorded"
      | "CreatorManualReviewUpdated"
      | "CreatorRestrictedUpdated"
      | "CreatorTierUpdated"
      | "CreatorTrustScoreUpdated"
      | "LaunchRecorderUpdated"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "canLaunch",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCreatorProfile",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCreatorRules",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRulesForTier",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "launchRecorder",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordGraduation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordLaunch",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setCreatorRestricted",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setCreatorTier",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCreatorTrustScore",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setLaunchRecorder",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setManualReviewRequired",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "canLaunch", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCreatorProfile",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCreatorRules",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRulesForTier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "launchRecorder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordGraduation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordLaunch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCreatorRestricted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCreatorTier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCreatorTrustScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLaunchRecorder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setManualReviewRequired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace CreatorGraduationRecordedEvent {
  export type InputTuple = [
    creator: AddressLike,
    liveBondingCount: BigNumberish
  ];
  export type OutputTuple = [creator: string, liveBondingCount: bigint];
  export interface OutputObject {
    creator: string;
    liveBondingCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreatorLaunchRecordedEvent {
  export type InputTuple = [
    creator: AddressLike,
    liveBondingCount: BigNumberish,
    launchedAt: BigNumberish
  ];
  export type OutputTuple = [
    creator: string,
    liveBondingCount: bigint,
    launchedAt: bigint
  ];
  export interface OutputObject {
    creator: string;
    liveBondingCount: bigint;
    launchedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreatorManualReviewUpdatedEvent {
  export type InputTuple = [
    creator: AddressLike,
    manualReviewRequired: boolean
  ];
  export type OutputTuple = [creator: string, manualReviewRequired: boolean];
  export interface OutputObject {
    creator: string;
    manualReviewRequired: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreatorRestrictedUpdatedEvent {
  export type InputTuple = [creator: AddressLike, restricted: boolean];
  export type OutputTuple = [creator: string, restricted: boolean];
  export interface OutputObject {
    creator: string;
    restricted: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreatorTierUpdatedEvent {
  export type InputTuple = [creator: AddressLike, tier: BigNumberish];
  export type OutputTuple = [creator: string, tier: bigint];
  export interface OutputObject {
    creator: string;
    tier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CreatorTrustScoreUpdatedEvent {
  export type InputTuple = [creator: AddressLike, trustScore: BigNumberish];
  export type OutputTuple = [creator: string, trustScore: bigint];
  export interface OutputObject {
    creator: string;
    trustScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LaunchRecorderUpdatedEvent {
  export type InputTuple = [recorder: AddressLike, allowed: boolean];
  export type OutputTuple = [recorder: string, allowed: boolean];
  export interface OutputObject {
    recorder: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CreatorRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): CreatorRegistry;
  waitForDeployment(): Promise<this>;

  interface: CreatorRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  canLaunch: TypedContractMethod<[creator: AddressLike], [boolean], "view">;

  getCreatorProfile: TypedContractMethod<
    [creator: AddressLike],
    [CreatorRegistry.CreatorProfileStructOutput],
    "view"
  >;

  getCreatorRules: TypedContractMethod<
    [creator: AddressLike],
    [CreatorRegistry.CreatorRulesStructOutput],
    "view"
  >;

  getRulesForTier: TypedContractMethod<
    [tier: BigNumberish],
    [CreatorRegistry.CreatorRulesStructOutput],
    "view"
  >;

  launchRecorder: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  recordGraduation: TypedContractMethod<
    [creator: AddressLike],
    [void],
    "nonpayable"
  >;

  recordLaunch: TypedContractMethod<
    [creator: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setCreatorRestricted: TypedContractMethod<
    [creator: AddressLike, restricted: boolean],
    [void],
    "nonpayable"
  >;

  setCreatorTier: TypedContractMethod<
    [creator: AddressLike, tier: BigNumberish],
    [void],
    "nonpayable"
  >;

  setCreatorTrustScore: TypedContractMethod<
    [creator: AddressLike, trustScore: BigNumberish],
    [void],
    "nonpayable"
  >;

  setLaunchRecorder: TypedContractMethod<
    [recorder: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;

  setManualReviewRequired: TypedContractMethod<
    [creator: AddressLike, required: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "canLaunch"
  ): TypedContractMethod<[creator: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getCreatorProfile"
  ): TypedContractMethod<
    [creator: AddressLike],
    [CreatorRegistry.CreatorProfileStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCreatorRules"
  ): TypedContractMethod<
    [creator: AddressLike],
    [CreatorRegistry.CreatorRulesStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRulesForTier"
  ): TypedContractMethod<
    [tier: BigNumberish],
    [CreatorRegistry.CreatorRulesStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "launchRecorder"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordGraduation"
  ): TypedContractMethod<[creator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "recordLaunch"
  ): TypedContractMethod<[creator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setCreatorRestricted"
  ): TypedContractMethod<
    [creator: AddressLike, restricted: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCreatorTier"
  ): TypedContractMethod<
    [creator: AddressLike, tier: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCreatorTrustScore"
  ): TypedContractMethod<
    [creator: AddressLike, trustScore: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setLaunchRecorder"
  ): TypedContractMethod<
    [recorder: AddressLike, allowed: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setManualReviewRequired"
  ): TypedContractMethod<
    [creator: AddressLike, required: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CreatorGraduationRecorded"
  ): TypedContractEvent<
    CreatorGraduationRecordedEvent.InputTuple,
    CreatorGraduationRecordedEvent.OutputTuple,
    CreatorGraduationRecordedEvent.OutputObject
  >;
  getEvent(
    key: "CreatorLaunchRecorded"
  ): TypedContractEvent<
    CreatorLaunchRecordedEvent.InputTuple,
    CreatorLaunchRecordedEvent.OutputTuple,
    CreatorLaunchRecordedEvent.OutputObject
  >;
  getEvent(
    key: "CreatorManualReviewUpdated"
  ): TypedContractEvent<
    CreatorManualReviewUpdatedEvent.InputTuple,
    CreatorManualReviewUpdatedEvent.OutputTuple,
    CreatorManualReviewUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CreatorRestrictedUpdated"
  ): TypedContractEvent<
    CreatorRestrictedUpdatedEvent.InputTuple,
    CreatorRestrictedUpdatedEvent.OutputTuple,
    CreatorRestrictedUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CreatorTierUpdated"
  ): TypedContractEvent<
    CreatorTierUpdatedEvent.InputTuple,
    CreatorTierUpdatedEvent.OutputTuple,
    CreatorTierUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "CreatorTrustScoreUpdated"
  ): TypedContractEvent<
    CreatorTrustScoreUpdatedEvent.InputTuple,
    CreatorTrustScoreUpdatedEvent.OutputTuple,
    CreatorTrustScoreUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "LaunchRecorderUpdated"
  ): TypedContractEvent<
    LaunchRecorderUpdatedEvent.InputTuple,
    LaunchRecorderUpdatedEvent.OutputTuple,
    LaunchRecorderUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "CreatorGraduationRecorded(address,uint256)": TypedContractEvent<
      CreatorGraduationRecordedEvent.InputTuple,
      CreatorGraduationRecordedEvent.OutputTuple,
      CreatorGraduationRecordedEvent.OutputObject
    >;
    CreatorGraduationRecorded: TypedContractEvent<
      CreatorGraduationRecordedEvent.InputTuple,
      CreatorGraduationRecordedEvent.OutputTuple,
      CreatorGraduationRecordedEvent.OutputObject
    >;

    "CreatorLaunchRecorded(address,uint256,uint256)": TypedContractEvent<
      CreatorLaunchRecordedEvent.InputTuple,
      CreatorLaunchRecordedEvent.OutputTuple,
      CreatorLaunchRecordedEvent.OutputObject
    >;
    CreatorLaunchRecorded: TypedContractEvent<
      CreatorLaunchRecordedEvent.InputTuple,
      CreatorLaunchRecordedEvent.OutputTuple,
      CreatorLaunchRecordedEvent.OutputObject
    >;

    "CreatorManualReviewUpdated(address,bool)": TypedContractEvent<
      CreatorManualReviewUpdatedEvent.InputTuple,
      CreatorManualReviewUpdatedEvent.OutputTuple,
      CreatorManualReviewUpdatedEvent.OutputObject
    >;
    CreatorManualReviewUpdated: TypedContractEvent<
      CreatorManualReviewUpdatedEvent.InputTuple,
      CreatorManualReviewUpdatedEvent.OutputTuple,
      CreatorManualReviewUpdatedEvent.OutputObject
    >;

    "CreatorRestrictedUpdated(address,bool)": TypedContractEvent<
      CreatorRestrictedUpdatedEvent.InputTuple,
      CreatorRestrictedUpdatedEvent.OutputTuple,
      CreatorRestrictedUpdatedEvent.OutputObject
    >;
    CreatorRestrictedUpdated: TypedContractEvent<
      CreatorRestrictedUpdatedEvent.InputTuple,
      CreatorRestrictedUpdatedEvent.OutputTuple,
      CreatorRestrictedUpdatedEvent.OutputObject
    >;

    "CreatorTierUpdated(address,uint8)": TypedContractEvent<
      CreatorTierUpdatedEvent.InputTuple,
      CreatorTierUpdatedEvent.OutputTuple,
      CreatorTierUpdatedEvent.OutputObject
    >;
    CreatorTierUpdated: TypedContractEvent<
      CreatorTierUpdatedEvent.InputTuple,
      CreatorTierUpdatedEvent.OutputTuple,
      CreatorTierUpdatedEvent.OutputObject
    >;

    "CreatorTrustScoreUpdated(address,uint256)": TypedContractEvent<
      CreatorTrustScoreUpdatedEvent.InputTuple,
      CreatorTrustScoreUpdatedEvent.OutputTuple,
      CreatorTrustScoreUpdatedEvent.OutputObject
    >;
    CreatorTrustScoreUpdated: TypedContractEvent<
      CreatorTrustScoreUpdatedEvent.InputTuple,
      CreatorTrustScoreUpdatedEvent.OutputTuple,
      CreatorTrustScoreUpdatedEvent.OutputObject
    >;

    "LaunchRecorderUpdated(address,bool)": TypedContractEvent<
      LaunchRecorderUpdatedEvent.InputTuple,
      LaunchRecorderUpdatedEvent.OutputTuple,
      LaunchRecorderUpdatedEvent.OutputObject
    >;
    LaunchRecorderUpdated: TypedContractEvent<
      LaunchRecorderUpdatedEvent.InputTuple,
      LaunchRecorderUpdatedEvent.OutputTuple,
      LaunchRecorderUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
