/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MajorLeagueTreasuryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "TIMELOCK_DELAY"
      | "allocateReward"
      | "allocateUnallocatedToPool"
      | "battleTreasurySource"
      | "cancelPendingBattleTreasurySource"
      | "cancelPendingDistributorChange"
      | "cancelPendingDistributorLimitUpdate"
      | "cancelPendingFeeRedirect"
      | "cancelPendingMaxAllocationPerTx"
      | "cancelPendingProtocolFeeReceiver"
      | "cancelPendingSeasonalTreasuryReceiver"
      | "cancelPendingSponsorshipPaymentsSource"
      | "claimPendingFees"
      | "claimReward"
      | "claimRewardTo"
      | "distributorDailyLimit"
      | "distributorDailySpent"
      | "distributorLastDay"
      | "distributorMaxPerTx"
      | "distributors"
      | "executeBattleTreasurySource"
      | "executeDistributorChange"
      | "executeDistributorLimitUpdate"
      | "executeFeeRedirect"
      | "executeMaxAllocationPerTx"
      | "executeProtocolFeeReceiver"
      | "executeSeasonalTreasuryReceiver"
      | "executeSponsorshipPaymentsSource"
      | "fundPrizePool"
      | "getClaimableAmount"
      | "getNetClaimableAmount"
      | "getPendingReward"
      | "getPrizePoolBalance"
      | "maxAllocationPerTx"
      | "owner"
      | "paused"
      | "pendingBattleTreasurySource"
      | "pendingDistributorChange"
      | "pendingDistributorLimitUpdate"
      | "pendingFeeRedirect"
      | "pendingFeeWithdrawals"
      | "pendingMaxAllocationPerTx"
      | "pendingProtocolFeeReceiver"
      | "pendingRewards"
      | "pendingSeasonalTreasuryReceiver"
      | "pendingSponsorshipPaymentsSource"
      | "prizePools"
      | "proposeBattleTreasurySource"
      | "proposeDistributorChange"
      | "proposeDistributorLimitUpdate"
      | "proposeFeeRedirect"
      | "proposeMaxAllocationPerTx"
      | "proposeProtocolFeeReceiver"
      | "proposeSeasonalTreasuryReceiver"
      | "proposeSponsorshipPaymentsSource"
      | "protocolFeeBps"
      | "protocolFeeReceiver"
      | "receiveBattleCut"
      | "receiveSponsorshipCut"
      | "renounceOwnership"
      | "retryPendingFee"
      | "seasonalFeeBps"
      | "seasonalTreasuryReceiver"
      | "setPaused"
      | "sponsorshipPaymentsSource"
      | "transferOwnership"
      | "unallocatedBalance"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BattleCutReceived"
      | "BattleTreasurySourceExecuted"
      | "BattleTreasurySourceProposed"
      | "DistributorChangeExecuted"
      | "DistributorChangeProposed"
      | "DistributorLimitUpdateExecuted"
      | "DistributorLimitUpdateProposed"
      | "DistributorUpdated"
      | "FeeRetrySucceeded"
      | "FeeTransferFailed"
      | "FeesDistributed"
      | "MaxAllocationPerTxExecuted"
      | "MaxAllocationPerTxProposed"
      | "OwnershipTransferred"
      | "PendingDistributorChangeCancelled"
      | "PendingDistributorLimitUpdateCancelled"
      | "PendingFeeRedirectCancelled"
      | "PendingFeeRedirectExecuted"
      | "PendingFeeRedirectProposed"
      | "PendingMaxAllocationPerTxCancelled"
      | "PendingProtocolFeeReceiverCancelled"
      | "PendingSeasonalTreasuryReceiverCancelled"
      | "PrizeFunded"
      | "ProtocolFeeReceiverExecuted"
      | "ProtocolFeeReceiverProposed"
      | "RewardAllocated"
      | "RewardClaimed"
      | "SeasonalTreasuryReceiverExecuted"
      | "SeasonalTreasuryReceiverProposed"
      | "SponsorshipCutReceived"
      | "SponsorshipPaymentsSourceExecuted"
      | "SponsorshipPaymentsSourceProposed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "TIMELOCK_DELAY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allocateReward",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allocateUnallocatedToPool",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "battleTreasurySource",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelPendingBattleTreasurySource",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelPendingDistributorChange",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelPendingDistributorLimitUpdate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelPendingFeeRedirect",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelPendingMaxAllocationPerTx",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelPendingProtocolFeeReceiver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelPendingSeasonalTreasuryReceiver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelPendingSponsorshipPaymentsSource",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimPendingFees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimReward",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRewardTo",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributorDailyLimit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributorDailySpent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributorLastDay",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributorMaxPerTx",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributors",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeBattleTreasurySource",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeDistributorChange",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeDistributorLimitUpdate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeFeeRedirect",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeMaxAllocationPerTx",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeProtocolFeeReceiver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeSeasonalTreasuryReceiver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeSponsorshipPaymentsSource",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fundPrizePool",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimableAmount",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNetClaimableAmount",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingReward",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPrizePoolBalance",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxAllocationPerTx",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingBattleTreasurySource",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingDistributorChange",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingDistributorLimitUpdate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingFeeRedirect",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingFeeWithdrawals",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingMaxAllocationPerTx",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingProtocolFeeReceiver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingRewards",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingSeasonalTreasuryReceiver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingSponsorshipPaymentsSource",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "prizePools",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeBattleTreasurySource",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeDistributorChange",
    values: [AddressLike, boolean, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeDistributorLimitUpdate",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeFeeRedirect",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeMaxAllocationPerTx",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeProtocolFeeReceiver",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeSeasonalTreasuryReceiver",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeSponsorshipPaymentsSource",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "protocolFeeReceiver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "receiveBattleCut",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveSponsorshipCut",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "retryPendingFee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "seasonalFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "seasonalTreasuryReceiver",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "setPaused", values: [boolean]): string;
  encodeFunctionData(
    functionFragment: "sponsorshipPaymentsSource",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unallocatedBalance",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "TIMELOCK_DELAY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allocateReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allocateUnallocatedToPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "battleTreasurySource",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelPendingBattleTreasurySource",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelPendingDistributorChange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelPendingDistributorLimitUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelPendingFeeRedirect",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelPendingMaxAllocationPerTx",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelPendingProtocolFeeReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelPendingSeasonalTreasuryReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelPendingSponsorshipPaymentsSource",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimPendingFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRewardTo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributorDailyLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributorDailySpent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributorLastDay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributorMaxPerTx",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeBattleTreasurySource",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeDistributorChange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeDistributorLimitUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeFeeRedirect",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeMaxAllocationPerTx",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeProtocolFeeReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeSeasonalTreasuryReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeSponsorshipPaymentsSource",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundPrizePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClaimableAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNetClaimableAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPrizePoolBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxAllocationPerTx",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingBattleTreasurySource",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingDistributorChange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingDistributorLimitUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingFeeRedirect",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingFeeWithdrawals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingMaxAllocationPerTx",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingProtocolFeeReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingSeasonalTreasuryReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingSponsorshipPaymentsSource",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "prizePools", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposeBattleTreasurySource",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeDistributorChange",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeDistributorLimitUpdate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeFeeRedirect",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeMaxAllocationPerTx",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeProtocolFeeReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeSeasonalTreasuryReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeSponsorshipPaymentsSource",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolFeeReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveBattleCut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveSponsorshipCut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "retryPendingFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seasonalFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seasonalTreasuryReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPaused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sponsorshipPaymentsSource",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unallocatedBalance",
    data: BytesLike
  ): Result;
}

export namespace BattleCutReceivedEvent {
  export type InputTuple = [
    battleId: BytesLike,
    poolId: BytesLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [battleId: string, poolId: string, amount: bigint];
  export interface OutputObject {
    battleId: string;
    poolId: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BattleTreasurySourceExecutedEvent {
  export type InputTuple = [newSource: AddressLike];
  export type OutputTuple = [newSource: string];
  export interface OutputObject {
    newSource: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BattleTreasurySourceProposedEvent {
  export type InputTuple = [newSource: AddressLike, executeAfter: BigNumberish];
  export type OutputTuple = [newSource: string, executeAfter: bigint];
  export interface OutputObject {
    newSource: string;
    executeAfter: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DistributorChangeExecutedEvent {
  export type InputTuple = [
    distributor: AddressLike,
    allowed: boolean,
    dailyLimit: BigNumberish,
    maxPerTx: BigNumberish
  ];
  export type OutputTuple = [
    distributor: string,
    allowed: boolean,
    dailyLimit: bigint,
    maxPerTx: bigint
  ];
  export interface OutputObject {
    distributor: string;
    allowed: boolean;
    dailyLimit: bigint;
    maxPerTx: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DistributorChangeProposedEvent {
  export type InputTuple = [
    distributor: AddressLike,
    allowed: boolean,
    dailyLimit: BigNumberish,
    maxPerTx: BigNumberish,
    executeAfter: BigNumberish
  ];
  export type OutputTuple = [
    distributor: string,
    allowed: boolean,
    dailyLimit: bigint,
    maxPerTx: bigint,
    executeAfter: bigint
  ];
  export interface OutputObject {
    distributor: string;
    allowed: boolean;
    dailyLimit: bigint;
    maxPerTx: bigint;
    executeAfter: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DistributorLimitUpdateExecutedEvent {
  export type InputTuple = [
    distributor: AddressLike,
    dailyLimit: BigNumberish,
    maxPerTx: BigNumberish
  ];
  export type OutputTuple = [
    distributor: string,
    dailyLimit: bigint,
    maxPerTx: bigint
  ];
  export interface OutputObject {
    distributor: string;
    dailyLimit: bigint;
    maxPerTx: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DistributorLimitUpdateProposedEvent {
  export type InputTuple = [
    distributor: AddressLike,
    dailyLimit: BigNumberish,
    maxPerTx: BigNumberish,
    executeAfter: BigNumberish
  ];
  export type OutputTuple = [
    distributor: string,
    dailyLimit: bigint,
    maxPerTx: bigint,
    executeAfter: bigint
  ];
  export interface OutputObject {
    distributor: string;
    dailyLimit: bigint;
    maxPerTx: bigint;
    executeAfter: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DistributorUpdatedEvent {
  export type InputTuple = [distributor: AddressLike, allowed: boolean];
  export type OutputTuple = [distributor: string, allowed: boolean];
  export interface OutputObject {
    distributor: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeRetrySucceededEvent {
  export type InputTuple = [receiver: AddressLike, amount: BigNumberish];
  export type OutputTuple = [receiver: string, amount: bigint];
  export interface OutputObject {
    receiver: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeTransferFailedEvent {
  export type InputTuple = [
    receiver: AddressLike,
    amount: BigNumberish,
    poolId: BytesLike
  ];
  export type OutputTuple = [receiver: string, amount: bigint, poolId: string];
  export interface OutputObject {
    receiver: string;
    amount: bigint;
    poolId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeesDistributedEvent {
  export type InputTuple = [
    protocolFee: BigNumberish,
    seasonalFee: BigNumberish
  ];
  export type OutputTuple = [protocolFee: bigint, seasonalFee: bigint];
  export interface OutputObject {
    protocolFee: bigint;
    seasonalFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxAllocationPerTxExecutedEvent {
  export type InputTuple = [newMax: BigNumberish];
  export type OutputTuple = [newMax: bigint];
  export interface OutputObject {
    newMax: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxAllocationPerTxProposedEvent {
  export type InputTuple = [newMax: BigNumberish, executeAfter: BigNumberish];
  export type OutputTuple = [newMax: bigint, executeAfter: bigint];
  export interface OutputObject {
    newMax: bigint;
    executeAfter: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PendingDistributorChangeCancelledEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PendingDistributorLimitUpdateCancelledEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PendingFeeRedirectCancelledEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PendingFeeRedirectExecutedEvent {
  export type InputTuple = [
    oldReceiver: AddressLike,
    newReceiver: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    oldReceiver: string,
    newReceiver: string,
    amount: bigint
  ];
  export interface OutputObject {
    oldReceiver: string;
    newReceiver: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PendingFeeRedirectProposedEvent {
  export type InputTuple = [
    oldReceiver: AddressLike,
    newReceiver: AddressLike,
    amount: BigNumberish,
    executeAfter: BigNumberish
  ];
  export type OutputTuple = [
    oldReceiver: string,
    newReceiver: string,
    amount: bigint,
    executeAfter: bigint
  ];
  export interface OutputObject {
    oldReceiver: string;
    newReceiver: string;
    amount: bigint;
    executeAfter: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PendingMaxAllocationPerTxCancelledEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PendingProtocolFeeReceiverCancelledEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PendingSeasonalTreasuryReceiverCancelledEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrizeFundedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    amount: BigNumberish,
    from: AddressLike
  ];
  export type OutputTuple = [poolId: string, amount: bigint, from: string];
  export interface OutputObject {
    poolId: string;
    amount: bigint;
    from: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolFeeReceiverExecutedEvent {
  export type InputTuple = [newReceiver: AddressLike];
  export type OutputTuple = [newReceiver: string];
  export interface OutputObject {
    newReceiver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolFeeReceiverProposedEvent {
  export type InputTuple = [
    newReceiver: AddressLike,
    executeAfter: BigNumberish
  ];
  export type OutputTuple = [newReceiver: string, executeAfter: bigint];
  export interface OutputObject {
    newReceiver: string;
    executeAfter: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardAllocatedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [poolId: string, recipient: string, amount: bigint];
  export interface OutputObject {
    poolId: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardClaimedEvent {
  export type InputTuple = [
    poolId: BytesLike,
    recipient: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [poolId: string, recipient: string, amount: bigint];
  export interface OutputObject {
    poolId: string;
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SeasonalTreasuryReceiverExecutedEvent {
  export type InputTuple = [newReceiver: AddressLike];
  export type OutputTuple = [newReceiver: string];
  export interface OutputObject {
    newReceiver: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SeasonalTreasuryReceiverProposedEvent {
  export type InputTuple = [
    newReceiver: AddressLike,
    executeAfter: BigNumberish
  ];
  export type OutputTuple = [newReceiver: string, executeAfter: bigint];
  export interface OutputObject {
    newReceiver: string;
    executeAfter: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SponsorshipCutReceivedEvent {
  export type InputTuple = [
    sponsorshipId: BytesLike,
    poolId: BytesLike,
    amount: BigNumberish,
    from: AddressLike
  ];
  export type OutputTuple = [
    sponsorshipId: string,
    poolId: string,
    amount: bigint,
    from: string
  ];
  export interface OutputObject {
    sponsorshipId: string;
    poolId: string;
    amount: bigint;
    from: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SponsorshipPaymentsSourceExecutedEvent {
  export type InputTuple = [newSource: AddressLike];
  export type OutputTuple = [newSource: string];
  export interface OutputObject {
    newSource: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SponsorshipPaymentsSourceProposedEvent {
  export type InputTuple = [newSource: AddressLike, executeAfter: BigNumberish];
  export type OutputTuple = [newSource: string, executeAfter: bigint];
  export interface OutputObject {
    newSource: string;
    executeAfter: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MajorLeagueTreasury extends BaseContract {
  connect(runner?: ContractRunner | null): MajorLeagueTreasury;
  waitForDeployment(): Promise<this>;

  interface: MajorLeagueTreasuryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  TIMELOCK_DELAY: TypedContractMethod<[], [bigint], "view">;

  allocateReward: TypedContractMethod<
    [poolId: BytesLike, recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  allocateUnallocatedToPool: TypedContractMethod<
    [poolId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  battleTreasurySource: TypedContractMethod<[], [string], "view">;

  cancelPendingBattleTreasurySource: TypedContractMethod<
    [],
    [void],
    "nonpayable"
  >;

  cancelPendingDistributorChange: TypedContractMethod<[], [void], "nonpayable">;

  cancelPendingDistributorLimitUpdate: TypedContractMethod<
    [],
    [void],
    "nonpayable"
  >;

  cancelPendingFeeRedirect: TypedContractMethod<[], [void], "nonpayable">;

  cancelPendingMaxAllocationPerTx: TypedContractMethod<
    [],
    [void],
    "nonpayable"
  >;

  cancelPendingProtocolFeeReceiver: TypedContractMethod<
    [],
    [void],
    "nonpayable"
  >;

  cancelPendingSeasonalTreasuryReceiver: TypedContractMethod<
    [],
    [void],
    "nonpayable"
  >;

  cancelPendingSponsorshipPaymentsSource: TypedContractMethod<
    [],
    [void],
    "nonpayable"
  >;

  claimPendingFees: TypedContractMethod<[], [void], "nonpayable">;

  claimReward: TypedContractMethod<[poolId: BytesLike], [void], "nonpayable">;

  claimRewardTo: TypedContractMethod<
    [poolId: BytesLike, payoutAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  distributorDailyLimit: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  distributorDailySpent: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  distributorLastDay: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  distributorMaxPerTx: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  distributors: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  executeBattleTreasurySource: TypedContractMethod<[], [void], "nonpayable">;

  executeDistributorChange: TypedContractMethod<[], [void], "nonpayable">;

  executeDistributorLimitUpdate: TypedContractMethod<[], [void], "nonpayable">;

  executeFeeRedirect: TypedContractMethod<[], [void], "nonpayable">;

  executeMaxAllocationPerTx: TypedContractMethod<[], [void], "nonpayable">;

  executeProtocolFeeReceiver: TypedContractMethod<[], [void], "nonpayable">;

  executeSeasonalTreasuryReceiver: TypedContractMethod<
    [],
    [void],
    "nonpayable"
  >;

  executeSponsorshipPaymentsSource: TypedContractMethod<
    [],
    [void],
    "nonpayable"
  >;

  fundPrizePool: TypedContractMethod<[poolId: BytesLike], [void], "payable">;

  getClaimableAmount: TypedContractMethod<
    [poolId: BytesLike, user: AddressLike],
    [bigint],
    "view"
  >;

  getNetClaimableAmount: TypedContractMethod<
    [poolId: BytesLike, user: AddressLike],
    [bigint],
    "view"
  >;

  getPendingReward: TypedContractMethod<
    [poolId: BytesLike, user: AddressLike],
    [bigint],
    "view"
  >;

  getPrizePoolBalance: TypedContractMethod<
    [poolId: BytesLike],
    [bigint],
    "view"
  >;

  maxAllocationPerTx: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingBattleTreasurySource: TypedContractMethod<
    [],
    [
      [string, bigint, boolean] & {
        newValue: string;
        executeAfter: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  pendingDistributorChange: TypedContractMethod<
    [],
    [
      [string, boolean, bigint, bigint, bigint, boolean] & {
        distributor: string;
        allowed: boolean;
        dailyLimit: bigint;
        maxPerTx: bigint;
        executeAfter: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  pendingDistributorLimitUpdate: TypedContractMethod<
    [],
    [
      [string, bigint, bigint, bigint, boolean] & {
        distributor: string;
        dailyLimit: bigint;
        maxPerTx: bigint;
        executeAfter: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  pendingFeeRedirect: TypedContractMethod<
    [],
    [
      [string, string, bigint, bigint, boolean] & {
        oldReceiver: string;
        newReceiver: string;
        amount: bigint;
        executeAfter: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  pendingFeeWithdrawals: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  pendingMaxAllocationPerTx: TypedContractMethod<
    [],
    [
      [bigint, bigint, boolean] & {
        newValue: bigint;
        executeAfter: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  pendingProtocolFeeReceiver: TypedContractMethod<
    [],
    [
      [string, bigint, boolean] & {
        newValue: string;
        executeAfter: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  pendingRewards: TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  pendingSeasonalTreasuryReceiver: TypedContractMethod<
    [],
    [
      [string, bigint, boolean] & {
        newValue: string;
        executeAfter: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  pendingSponsorshipPaymentsSource: TypedContractMethod<
    [],
    [
      [string, bigint, boolean] & {
        newValue: string;
        executeAfter: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  prizePools: TypedContractMethod<[arg0: BytesLike], [bigint], "view">;

  proposeBattleTreasurySource: TypedContractMethod<
    [newSource: AddressLike],
    [void],
    "nonpayable"
  >;

  proposeDistributorChange: TypedContractMethod<
    [
      distributor: AddressLike,
      allowed: boolean,
      dailyLimit: BigNumberish,
      maxPerTx: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  proposeDistributorLimitUpdate: TypedContractMethod<
    [
      distributor: AddressLike,
      dailyLimit: BigNumberish,
      maxPerTx: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  proposeFeeRedirect: TypedContractMethod<
    [oldReceiver: AddressLike, newReceiver: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  proposeMaxAllocationPerTx: TypedContractMethod<
    [newMax: BigNumberish],
    [void],
    "nonpayable"
  >;

  proposeProtocolFeeReceiver: TypedContractMethod<
    [newReceiver: AddressLike],
    [void],
    "nonpayable"
  >;

  proposeSeasonalTreasuryReceiver: TypedContractMethod<
    [newReceiver: AddressLike],
    [void],
    "nonpayable"
  >;

  proposeSponsorshipPaymentsSource: TypedContractMethod<
    [newSource: AddressLike],
    [void],
    "nonpayable"
  >;

  protocolFeeBps: TypedContractMethod<[], [bigint], "view">;

  protocolFeeReceiver: TypedContractMethod<[], [string], "view">;

  receiveBattleCut: TypedContractMethod<
    [battleId: BytesLike, poolId: BytesLike],
    [void],
    "payable"
  >;

  receiveSponsorshipCut: TypedContractMethod<
    [sponsorshipId: BytesLike, poolId: BytesLike],
    [void],
    "payable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  retryPendingFee: TypedContractMethod<
    [receiver: AddressLike],
    [void],
    "nonpayable"
  >;

  seasonalFeeBps: TypedContractMethod<[], [bigint], "view">;

  seasonalTreasuryReceiver: TypedContractMethod<[], [string], "view">;

  setPaused: TypedContractMethod<[_paused: boolean], [void], "nonpayable">;

  sponsorshipPaymentsSource: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unallocatedBalance: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "TIMELOCK_DELAY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "allocateReward"
  ): TypedContractMethod<
    [poolId: BytesLike, recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "allocateUnallocatedToPool"
  ): TypedContractMethod<
    [poolId: BytesLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "battleTreasurySource"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancelPendingBattleTreasurySource"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelPendingDistributorChange"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelPendingDistributorLimitUpdate"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelPendingFeeRedirect"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelPendingMaxAllocationPerTx"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelPendingProtocolFeeReceiver"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelPendingSeasonalTreasuryReceiver"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelPendingSponsorshipPaymentsSource"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimPendingFees"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimReward"
  ): TypedContractMethod<[poolId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimRewardTo"
  ): TypedContractMethod<
    [poolId: BytesLike, payoutAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "distributorDailyLimit"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "distributorDailySpent"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "distributorLastDay"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "distributorMaxPerTx"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "distributors"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "executeBattleTreasurySource"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeDistributorChange"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeDistributorLimitUpdate"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeFeeRedirect"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeMaxAllocationPerTx"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeProtocolFeeReceiver"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeSeasonalTreasuryReceiver"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeSponsorshipPaymentsSource"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fundPrizePool"
  ): TypedContractMethod<[poolId: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "getClaimableAmount"
  ): TypedContractMethod<
    [poolId: BytesLike, user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getNetClaimableAmount"
  ): TypedContractMethod<
    [poolId: BytesLike, user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPendingReward"
  ): TypedContractMethod<
    [poolId: BytesLike, user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPrizePoolBalance"
  ): TypedContractMethod<[poolId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxAllocationPerTx"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingBattleTreasurySource"
  ): TypedContractMethod<
    [],
    [
      [string, bigint, boolean] & {
        newValue: string;
        executeAfter: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pendingDistributorChange"
  ): TypedContractMethod<
    [],
    [
      [string, boolean, bigint, bigint, bigint, boolean] & {
        distributor: string;
        allowed: boolean;
        dailyLimit: bigint;
        maxPerTx: bigint;
        executeAfter: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pendingDistributorLimitUpdate"
  ): TypedContractMethod<
    [],
    [
      [string, bigint, bigint, bigint, boolean] & {
        distributor: string;
        dailyLimit: bigint;
        maxPerTx: bigint;
        executeAfter: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pendingFeeRedirect"
  ): TypedContractMethod<
    [],
    [
      [string, string, bigint, bigint, boolean] & {
        oldReceiver: string;
        newReceiver: string;
        amount: bigint;
        executeAfter: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pendingFeeWithdrawals"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "pendingMaxAllocationPerTx"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, boolean] & {
        newValue: bigint;
        executeAfter: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pendingProtocolFeeReceiver"
  ): TypedContractMethod<
    [],
    [
      [string, bigint, boolean] & {
        newValue: string;
        executeAfter: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pendingRewards"
  ): TypedContractMethod<
    [arg0: BytesLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "pendingSeasonalTreasuryReceiver"
  ): TypedContractMethod<
    [],
    [
      [string, bigint, boolean] & {
        newValue: string;
        executeAfter: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pendingSponsorshipPaymentsSource"
  ): TypedContractMethod<
    [],
    [
      [string, bigint, boolean] & {
        newValue: string;
        executeAfter: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "prizePools"
  ): TypedContractMethod<[arg0: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "proposeBattleTreasurySource"
  ): TypedContractMethod<[newSource: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "proposeDistributorChange"
  ): TypedContractMethod<
    [
      distributor: AddressLike,
      allowed: boolean,
      dailyLimit: BigNumberish,
      maxPerTx: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "proposeDistributorLimitUpdate"
  ): TypedContractMethod<
    [
      distributor: AddressLike,
      dailyLimit: BigNumberish,
      maxPerTx: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "proposeFeeRedirect"
  ): TypedContractMethod<
    [oldReceiver: AddressLike, newReceiver: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "proposeMaxAllocationPerTx"
  ): TypedContractMethod<[newMax: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "proposeProtocolFeeReceiver"
  ): TypedContractMethod<[newReceiver: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "proposeSeasonalTreasuryReceiver"
  ): TypedContractMethod<[newReceiver: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "proposeSponsorshipPaymentsSource"
  ): TypedContractMethod<[newSource: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "protocolFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "protocolFeeReceiver"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "receiveBattleCut"
  ): TypedContractMethod<
    [battleId: BytesLike, poolId: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "receiveSponsorshipCut"
  ): TypedContractMethod<
    [sponsorshipId: BytesLike, poolId: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "retryPendingFee"
  ): TypedContractMethod<[receiver: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "seasonalFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "seasonalTreasuryReceiver"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setPaused"
  ): TypedContractMethod<[_paused: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sponsorshipPaymentsSource"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unallocatedBalance"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "BattleCutReceived"
  ): TypedContractEvent<
    BattleCutReceivedEvent.InputTuple,
    BattleCutReceivedEvent.OutputTuple,
    BattleCutReceivedEvent.OutputObject
  >;
  getEvent(
    key: "BattleTreasurySourceExecuted"
  ): TypedContractEvent<
    BattleTreasurySourceExecutedEvent.InputTuple,
    BattleTreasurySourceExecutedEvent.OutputTuple,
    BattleTreasurySourceExecutedEvent.OutputObject
  >;
  getEvent(
    key: "BattleTreasurySourceProposed"
  ): TypedContractEvent<
    BattleTreasurySourceProposedEvent.InputTuple,
    BattleTreasurySourceProposedEvent.OutputTuple,
    BattleTreasurySourceProposedEvent.OutputObject
  >;
  getEvent(
    key: "DistributorChangeExecuted"
  ): TypedContractEvent<
    DistributorChangeExecutedEvent.InputTuple,
    DistributorChangeExecutedEvent.OutputTuple,
    DistributorChangeExecutedEvent.OutputObject
  >;
  getEvent(
    key: "DistributorChangeProposed"
  ): TypedContractEvent<
    DistributorChangeProposedEvent.InputTuple,
    DistributorChangeProposedEvent.OutputTuple,
    DistributorChangeProposedEvent.OutputObject
  >;
  getEvent(
    key: "DistributorLimitUpdateExecuted"
  ): TypedContractEvent<
    DistributorLimitUpdateExecutedEvent.InputTuple,
    DistributorLimitUpdateExecutedEvent.OutputTuple,
    DistributorLimitUpdateExecutedEvent.OutputObject
  >;
  getEvent(
    key: "DistributorLimitUpdateProposed"
  ): TypedContractEvent<
    DistributorLimitUpdateProposedEvent.InputTuple,
    DistributorLimitUpdateProposedEvent.OutputTuple,
    DistributorLimitUpdateProposedEvent.OutputObject
  >;
  getEvent(
    key: "DistributorUpdated"
  ): TypedContractEvent<
    DistributorUpdatedEvent.InputTuple,
    DistributorUpdatedEvent.OutputTuple,
    DistributorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "FeeRetrySucceeded"
  ): TypedContractEvent<
    FeeRetrySucceededEvent.InputTuple,
    FeeRetrySucceededEvent.OutputTuple,
    FeeRetrySucceededEvent.OutputObject
  >;
  getEvent(
    key: "FeeTransferFailed"
  ): TypedContractEvent<
    FeeTransferFailedEvent.InputTuple,
    FeeTransferFailedEvent.OutputTuple,
    FeeTransferFailedEvent.OutputObject
  >;
  getEvent(
    key: "FeesDistributed"
  ): TypedContractEvent<
    FeesDistributedEvent.InputTuple,
    FeesDistributedEvent.OutputTuple,
    FeesDistributedEvent.OutputObject
  >;
  getEvent(
    key: "MaxAllocationPerTxExecuted"
  ): TypedContractEvent<
    MaxAllocationPerTxExecutedEvent.InputTuple,
    MaxAllocationPerTxExecutedEvent.OutputTuple,
    MaxAllocationPerTxExecutedEvent.OutputObject
  >;
  getEvent(
    key: "MaxAllocationPerTxProposed"
  ): TypedContractEvent<
    MaxAllocationPerTxProposedEvent.InputTuple,
    MaxAllocationPerTxProposedEvent.OutputTuple,
    MaxAllocationPerTxProposedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PendingDistributorChangeCancelled"
  ): TypedContractEvent<
    PendingDistributorChangeCancelledEvent.InputTuple,
    PendingDistributorChangeCancelledEvent.OutputTuple,
    PendingDistributorChangeCancelledEvent.OutputObject
  >;
  getEvent(
    key: "PendingDistributorLimitUpdateCancelled"
  ): TypedContractEvent<
    PendingDistributorLimitUpdateCancelledEvent.InputTuple,
    PendingDistributorLimitUpdateCancelledEvent.OutputTuple,
    PendingDistributorLimitUpdateCancelledEvent.OutputObject
  >;
  getEvent(
    key: "PendingFeeRedirectCancelled"
  ): TypedContractEvent<
    PendingFeeRedirectCancelledEvent.InputTuple,
    PendingFeeRedirectCancelledEvent.OutputTuple,
    PendingFeeRedirectCancelledEvent.OutputObject
  >;
  getEvent(
    key: "PendingFeeRedirectExecuted"
  ): TypedContractEvent<
    PendingFeeRedirectExecutedEvent.InputTuple,
    PendingFeeRedirectExecutedEvent.OutputTuple,
    PendingFeeRedirectExecutedEvent.OutputObject
  >;
  getEvent(
    key: "PendingFeeRedirectProposed"
  ): TypedContractEvent<
    PendingFeeRedirectProposedEvent.InputTuple,
    PendingFeeRedirectProposedEvent.OutputTuple,
    PendingFeeRedirectProposedEvent.OutputObject
  >;
  getEvent(
    key: "PendingMaxAllocationPerTxCancelled"
  ): TypedContractEvent<
    PendingMaxAllocationPerTxCancelledEvent.InputTuple,
    PendingMaxAllocationPerTxCancelledEvent.OutputTuple,
    PendingMaxAllocationPerTxCancelledEvent.OutputObject
  >;
  getEvent(
    key: "PendingProtocolFeeReceiverCancelled"
  ): TypedContractEvent<
    PendingProtocolFeeReceiverCancelledEvent.InputTuple,
    PendingProtocolFeeReceiverCancelledEvent.OutputTuple,
    PendingProtocolFeeReceiverCancelledEvent.OutputObject
  >;
  getEvent(
    key: "PendingSeasonalTreasuryReceiverCancelled"
  ): TypedContractEvent<
    PendingSeasonalTreasuryReceiverCancelledEvent.InputTuple,
    PendingSeasonalTreasuryReceiverCancelledEvent.OutputTuple,
    PendingSeasonalTreasuryReceiverCancelledEvent.OutputObject
  >;
  getEvent(
    key: "PrizeFunded"
  ): TypedContractEvent<
    PrizeFundedEvent.InputTuple,
    PrizeFundedEvent.OutputTuple,
    PrizeFundedEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolFeeReceiverExecuted"
  ): TypedContractEvent<
    ProtocolFeeReceiverExecutedEvent.InputTuple,
    ProtocolFeeReceiverExecutedEvent.OutputTuple,
    ProtocolFeeReceiverExecutedEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolFeeReceiverProposed"
  ): TypedContractEvent<
    ProtocolFeeReceiverProposedEvent.InputTuple,
    ProtocolFeeReceiverProposedEvent.OutputTuple,
    ProtocolFeeReceiverProposedEvent.OutputObject
  >;
  getEvent(
    key: "RewardAllocated"
  ): TypedContractEvent<
    RewardAllocatedEvent.InputTuple,
    RewardAllocatedEvent.OutputTuple,
    RewardAllocatedEvent.OutputObject
  >;
  getEvent(
    key: "RewardClaimed"
  ): TypedContractEvent<
    RewardClaimedEvent.InputTuple,
    RewardClaimedEvent.OutputTuple,
    RewardClaimedEvent.OutputObject
  >;
  getEvent(
    key: "SeasonalTreasuryReceiverExecuted"
  ): TypedContractEvent<
    SeasonalTreasuryReceiverExecutedEvent.InputTuple,
    SeasonalTreasuryReceiverExecutedEvent.OutputTuple,
    SeasonalTreasuryReceiverExecutedEvent.OutputObject
  >;
  getEvent(
    key: "SeasonalTreasuryReceiverProposed"
  ): TypedContractEvent<
    SeasonalTreasuryReceiverProposedEvent.InputTuple,
    SeasonalTreasuryReceiverProposedEvent.OutputTuple,
    SeasonalTreasuryReceiverProposedEvent.OutputObject
  >;
  getEvent(
    key: "SponsorshipCutReceived"
  ): TypedContractEvent<
    SponsorshipCutReceivedEvent.InputTuple,
    SponsorshipCutReceivedEvent.OutputTuple,
    SponsorshipCutReceivedEvent.OutputObject
  >;
  getEvent(
    key: "SponsorshipPaymentsSourceExecuted"
  ): TypedContractEvent<
    SponsorshipPaymentsSourceExecutedEvent.InputTuple,
    SponsorshipPaymentsSourceExecutedEvent.OutputTuple,
    SponsorshipPaymentsSourceExecutedEvent.OutputObject
  >;
  getEvent(
    key: "SponsorshipPaymentsSourceProposed"
  ): TypedContractEvent<
    SponsorshipPaymentsSourceProposedEvent.InputTuple,
    SponsorshipPaymentsSourceProposedEvent.OutputTuple,
    SponsorshipPaymentsSourceProposedEvent.OutputObject
  >;

  filters: {
    "BattleCutReceived(bytes32,bytes32,uint256)": TypedContractEvent<
      BattleCutReceivedEvent.InputTuple,
      BattleCutReceivedEvent.OutputTuple,
      BattleCutReceivedEvent.OutputObject
    >;
    BattleCutReceived: TypedContractEvent<
      BattleCutReceivedEvent.InputTuple,
      BattleCutReceivedEvent.OutputTuple,
      BattleCutReceivedEvent.OutputObject
    >;

    "BattleTreasurySourceExecuted(address)": TypedContractEvent<
      BattleTreasurySourceExecutedEvent.InputTuple,
      BattleTreasurySourceExecutedEvent.OutputTuple,
      BattleTreasurySourceExecutedEvent.OutputObject
    >;
    BattleTreasurySourceExecuted: TypedContractEvent<
      BattleTreasurySourceExecutedEvent.InputTuple,
      BattleTreasurySourceExecutedEvent.OutputTuple,
      BattleTreasurySourceExecutedEvent.OutputObject
    >;

    "BattleTreasurySourceProposed(address,uint256)": TypedContractEvent<
      BattleTreasurySourceProposedEvent.InputTuple,
      BattleTreasurySourceProposedEvent.OutputTuple,
      BattleTreasurySourceProposedEvent.OutputObject
    >;
    BattleTreasurySourceProposed: TypedContractEvent<
      BattleTreasurySourceProposedEvent.InputTuple,
      BattleTreasurySourceProposedEvent.OutputTuple,
      BattleTreasurySourceProposedEvent.OutputObject
    >;

    "DistributorChangeExecuted(address,bool,uint256,uint256)": TypedContractEvent<
      DistributorChangeExecutedEvent.InputTuple,
      DistributorChangeExecutedEvent.OutputTuple,
      DistributorChangeExecutedEvent.OutputObject
    >;
    DistributorChangeExecuted: TypedContractEvent<
      DistributorChangeExecutedEvent.InputTuple,
      DistributorChangeExecutedEvent.OutputTuple,
      DistributorChangeExecutedEvent.OutputObject
    >;

    "DistributorChangeProposed(address,bool,uint256,uint256,uint256)": TypedContractEvent<
      DistributorChangeProposedEvent.InputTuple,
      DistributorChangeProposedEvent.OutputTuple,
      DistributorChangeProposedEvent.OutputObject
    >;
    DistributorChangeProposed: TypedContractEvent<
      DistributorChangeProposedEvent.InputTuple,
      DistributorChangeProposedEvent.OutputTuple,
      DistributorChangeProposedEvent.OutputObject
    >;

    "DistributorLimitUpdateExecuted(address,uint256,uint256)": TypedContractEvent<
      DistributorLimitUpdateExecutedEvent.InputTuple,
      DistributorLimitUpdateExecutedEvent.OutputTuple,
      DistributorLimitUpdateExecutedEvent.OutputObject
    >;
    DistributorLimitUpdateExecuted: TypedContractEvent<
      DistributorLimitUpdateExecutedEvent.InputTuple,
      DistributorLimitUpdateExecutedEvent.OutputTuple,
      DistributorLimitUpdateExecutedEvent.OutputObject
    >;

    "DistributorLimitUpdateProposed(address,uint256,uint256,uint256)": TypedContractEvent<
      DistributorLimitUpdateProposedEvent.InputTuple,
      DistributorLimitUpdateProposedEvent.OutputTuple,
      DistributorLimitUpdateProposedEvent.OutputObject
    >;
    DistributorLimitUpdateProposed: TypedContractEvent<
      DistributorLimitUpdateProposedEvent.InputTuple,
      DistributorLimitUpdateProposedEvent.OutputTuple,
      DistributorLimitUpdateProposedEvent.OutputObject
    >;

    "DistributorUpdated(address,bool)": TypedContractEvent<
      DistributorUpdatedEvent.InputTuple,
      DistributorUpdatedEvent.OutputTuple,
      DistributorUpdatedEvent.OutputObject
    >;
    DistributorUpdated: TypedContractEvent<
      DistributorUpdatedEvent.InputTuple,
      DistributorUpdatedEvent.OutputTuple,
      DistributorUpdatedEvent.OutputObject
    >;

    "FeeRetrySucceeded(address,uint256)": TypedContractEvent<
      FeeRetrySucceededEvent.InputTuple,
      FeeRetrySucceededEvent.OutputTuple,
      FeeRetrySucceededEvent.OutputObject
    >;
    FeeRetrySucceeded: TypedContractEvent<
      FeeRetrySucceededEvent.InputTuple,
      FeeRetrySucceededEvent.OutputTuple,
      FeeRetrySucceededEvent.OutputObject
    >;

    "FeeTransferFailed(address,uint256,bytes32)": TypedContractEvent<
      FeeTransferFailedEvent.InputTuple,
      FeeTransferFailedEvent.OutputTuple,
      FeeTransferFailedEvent.OutputObject
    >;
    FeeTransferFailed: TypedContractEvent<
      FeeTransferFailedEvent.InputTuple,
      FeeTransferFailedEvent.OutputTuple,
      FeeTransferFailedEvent.OutputObject
    >;

    "FeesDistributed(uint256,uint256)": TypedContractEvent<
      FeesDistributedEvent.InputTuple,
      FeesDistributedEvent.OutputTuple,
      FeesDistributedEvent.OutputObject
    >;
    FeesDistributed: TypedContractEvent<
      FeesDistributedEvent.InputTuple,
      FeesDistributedEvent.OutputTuple,
      FeesDistributedEvent.OutputObject
    >;

    "MaxAllocationPerTxExecuted(uint256)": TypedContractEvent<
      MaxAllocationPerTxExecutedEvent.InputTuple,
      MaxAllocationPerTxExecutedEvent.OutputTuple,
      MaxAllocationPerTxExecutedEvent.OutputObject
    >;
    MaxAllocationPerTxExecuted: TypedContractEvent<
      MaxAllocationPerTxExecutedEvent.InputTuple,
      MaxAllocationPerTxExecutedEvent.OutputTuple,
      MaxAllocationPerTxExecutedEvent.OutputObject
    >;

    "MaxAllocationPerTxProposed(uint256,uint256)": TypedContractEvent<
      MaxAllocationPerTxProposedEvent.InputTuple,
      MaxAllocationPerTxProposedEvent.OutputTuple,
      MaxAllocationPerTxProposedEvent.OutputObject
    >;
    MaxAllocationPerTxProposed: TypedContractEvent<
      MaxAllocationPerTxProposedEvent.InputTuple,
      MaxAllocationPerTxProposedEvent.OutputTuple,
      MaxAllocationPerTxProposedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PendingDistributorChangeCancelled()": TypedContractEvent<
      PendingDistributorChangeCancelledEvent.InputTuple,
      PendingDistributorChangeCancelledEvent.OutputTuple,
      PendingDistributorChangeCancelledEvent.OutputObject
    >;
    PendingDistributorChangeCancelled: TypedContractEvent<
      PendingDistributorChangeCancelledEvent.InputTuple,
      PendingDistributorChangeCancelledEvent.OutputTuple,
      PendingDistributorChangeCancelledEvent.OutputObject
    >;

    "PendingDistributorLimitUpdateCancelled()": TypedContractEvent<
      PendingDistributorLimitUpdateCancelledEvent.InputTuple,
      PendingDistributorLimitUpdateCancelledEvent.OutputTuple,
      PendingDistributorLimitUpdateCancelledEvent.OutputObject
    >;
    PendingDistributorLimitUpdateCancelled: TypedContractEvent<
      PendingDistributorLimitUpdateCancelledEvent.InputTuple,
      PendingDistributorLimitUpdateCancelledEvent.OutputTuple,
      PendingDistributorLimitUpdateCancelledEvent.OutputObject
    >;

    "PendingFeeRedirectCancelled()": TypedContractEvent<
      PendingFeeRedirectCancelledEvent.InputTuple,
      PendingFeeRedirectCancelledEvent.OutputTuple,
      PendingFeeRedirectCancelledEvent.OutputObject
    >;
    PendingFeeRedirectCancelled: TypedContractEvent<
      PendingFeeRedirectCancelledEvent.InputTuple,
      PendingFeeRedirectCancelledEvent.OutputTuple,
      PendingFeeRedirectCancelledEvent.OutputObject
    >;

    "PendingFeeRedirectExecuted(address,address,uint256)": TypedContractEvent<
      PendingFeeRedirectExecutedEvent.InputTuple,
      PendingFeeRedirectExecutedEvent.OutputTuple,
      PendingFeeRedirectExecutedEvent.OutputObject
    >;
    PendingFeeRedirectExecuted: TypedContractEvent<
      PendingFeeRedirectExecutedEvent.InputTuple,
      PendingFeeRedirectExecutedEvent.OutputTuple,
      PendingFeeRedirectExecutedEvent.OutputObject
    >;

    "PendingFeeRedirectProposed(address,address,uint256,uint256)": TypedContractEvent<
      PendingFeeRedirectProposedEvent.InputTuple,
      PendingFeeRedirectProposedEvent.OutputTuple,
      PendingFeeRedirectProposedEvent.OutputObject
    >;
    PendingFeeRedirectProposed: TypedContractEvent<
      PendingFeeRedirectProposedEvent.InputTuple,
      PendingFeeRedirectProposedEvent.OutputTuple,
      PendingFeeRedirectProposedEvent.OutputObject
    >;

    "PendingMaxAllocationPerTxCancelled()": TypedContractEvent<
      PendingMaxAllocationPerTxCancelledEvent.InputTuple,
      PendingMaxAllocationPerTxCancelledEvent.OutputTuple,
      PendingMaxAllocationPerTxCancelledEvent.OutputObject
    >;
    PendingMaxAllocationPerTxCancelled: TypedContractEvent<
      PendingMaxAllocationPerTxCancelledEvent.InputTuple,
      PendingMaxAllocationPerTxCancelledEvent.OutputTuple,
      PendingMaxAllocationPerTxCancelledEvent.OutputObject
    >;

    "PendingProtocolFeeReceiverCancelled()": TypedContractEvent<
      PendingProtocolFeeReceiverCancelledEvent.InputTuple,
      PendingProtocolFeeReceiverCancelledEvent.OutputTuple,
      PendingProtocolFeeReceiverCancelledEvent.OutputObject
    >;
    PendingProtocolFeeReceiverCancelled: TypedContractEvent<
      PendingProtocolFeeReceiverCancelledEvent.InputTuple,
      PendingProtocolFeeReceiverCancelledEvent.OutputTuple,
      PendingProtocolFeeReceiverCancelledEvent.OutputObject
    >;

    "PendingSeasonalTreasuryReceiverCancelled()": TypedContractEvent<
      PendingSeasonalTreasuryReceiverCancelledEvent.InputTuple,
      PendingSeasonalTreasuryReceiverCancelledEvent.OutputTuple,
      PendingSeasonalTreasuryReceiverCancelledEvent.OutputObject
    >;
    PendingSeasonalTreasuryReceiverCancelled: TypedContractEvent<
      PendingSeasonalTreasuryReceiverCancelledEvent.InputTuple,
      PendingSeasonalTreasuryReceiverCancelledEvent.OutputTuple,
      PendingSeasonalTreasuryReceiverCancelledEvent.OutputObject
    >;

    "PrizeFunded(bytes32,uint256,address)": TypedContractEvent<
      PrizeFundedEvent.InputTuple,
      PrizeFundedEvent.OutputTuple,
      PrizeFundedEvent.OutputObject
    >;
    PrizeFunded: TypedContractEvent<
      PrizeFundedEvent.InputTuple,
      PrizeFundedEvent.OutputTuple,
      PrizeFundedEvent.OutputObject
    >;

    "ProtocolFeeReceiverExecuted(address)": TypedContractEvent<
      ProtocolFeeReceiverExecutedEvent.InputTuple,
      ProtocolFeeReceiverExecutedEvent.OutputTuple,
      ProtocolFeeReceiverExecutedEvent.OutputObject
    >;
    ProtocolFeeReceiverExecuted: TypedContractEvent<
      ProtocolFeeReceiverExecutedEvent.InputTuple,
      ProtocolFeeReceiverExecutedEvent.OutputTuple,
      ProtocolFeeReceiverExecutedEvent.OutputObject
    >;

    "ProtocolFeeReceiverProposed(address,uint256)": TypedContractEvent<
      ProtocolFeeReceiverProposedEvent.InputTuple,
      ProtocolFeeReceiverProposedEvent.OutputTuple,
      ProtocolFeeReceiverProposedEvent.OutputObject
    >;
    ProtocolFeeReceiverProposed: TypedContractEvent<
      ProtocolFeeReceiverProposedEvent.InputTuple,
      ProtocolFeeReceiverProposedEvent.OutputTuple,
      ProtocolFeeReceiverProposedEvent.OutputObject
    >;

    "RewardAllocated(bytes32,address,uint256)": TypedContractEvent<
      RewardAllocatedEvent.InputTuple,
      RewardAllocatedEvent.OutputTuple,
      RewardAllocatedEvent.OutputObject
    >;
    RewardAllocated: TypedContractEvent<
      RewardAllocatedEvent.InputTuple,
      RewardAllocatedEvent.OutputTuple,
      RewardAllocatedEvent.OutputObject
    >;

    "RewardClaimed(bytes32,address,uint256)": TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;
    RewardClaimed: TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;

    "SeasonalTreasuryReceiverExecuted(address)": TypedContractEvent<
      SeasonalTreasuryReceiverExecutedEvent.InputTuple,
      SeasonalTreasuryReceiverExecutedEvent.OutputTuple,
      SeasonalTreasuryReceiverExecutedEvent.OutputObject
    >;
    SeasonalTreasuryReceiverExecuted: TypedContractEvent<
      SeasonalTreasuryReceiverExecutedEvent.InputTuple,
      SeasonalTreasuryReceiverExecutedEvent.OutputTuple,
      SeasonalTreasuryReceiverExecutedEvent.OutputObject
    >;

    "SeasonalTreasuryReceiverProposed(address,uint256)": TypedContractEvent<
      SeasonalTreasuryReceiverProposedEvent.InputTuple,
      SeasonalTreasuryReceiverProposedEvent.OutputTuple,
      SeasonalTreasuryReceiverProposedEvent.OutputObject
    >;
    SeasonalTreasuryReceiverProposed: TypedContractEvent<
      SeasonalTreasuryReceiverProposedEvent.InputTuple,
      SeasonalTreasuryReceiverProposedEvent.OutputTuple,
      SeasonalTreasuryReceiverProposedEvent.OutputObject
    >;

    "SponsorshipCutReceived(bytes32,bytes32,uint256,address)": TypedContractEvent<
      SponsorshipCutReceivedEvent.InputTuple,
      SponsorshipCutReceivedEvent.OutputTuple,
      SponsorshipCutReceivedEvent.OutputObject
    >;
    SponsorshipCutReceived: TypedContractEvent<
      SponsorshipCutReceivedEvent.InputTuple,
      SponsorshipCutReceivedEvent.OutputTuple,
      SponsorshipCutReceivedEvent.OutputObject
    >;

    "SponsorshipPaymentsSourceExecuted(address)": TypedContractEvent<
      SponsorshipPaymentsSourceExecutedEvent.InputTuple,
      SponsorshipPaymentsSourceExecutedEvent.OutputTuple,
      SponsorshipPaymentsSourceExecutedEvent.OutputObject
    >;
    SponsorshipPaymentsSourceExecuted: TypedContractEvent<
      SponsorshipPaymentsSourceExecutedEvent.InputTuple,
      SponsorshipPaymentsSourceExecutedEvent.OutputTuple,
      SponsorshipPaymentsSourceExecutedEvent.OutputObject
    >;

    "SponsorshipPaymentsSourceProposed(address,uint256)": TypedContractEvent<
      SponsorshipPaymentsSourceProposedEvent.InputTuple,
      SponsorshipPaymentsSourceProposedEvent.OutputTuple,
      SponsorshipPaymentsSourceProposedEvent.OutputObject
    >;
    SponsorshipPaymentsSourceProposed: TypedContractEvent<
      SponsorshipPaymentsSourceProposedEvent.InputTuple,
      SponsorshipPaymentsSourceProposedEvent.OutputTuple,
      SponsorshipPaymentsSourceProposedEvent.OutputObject
    >;
  };
}
