create table if not exists public.ticker_reservations (
  id uuid primary key default gen_random_uuid(),
  draft_id uuid references public.campaign_drafts(id) on delete set null,
  creator_wallet text not null,
  chain_id integer not null,
  cluster text not null,
  original_ticker text not null,
  normalized_ticker text not null,
  ticker_hash text not null,
  reservation_id_hash text not null,
  status text not null,
  reserved_at timestamptz not null default now(),
  published_at timestamptz,
  expires_at timestamptz,
  grace_end_at timestamptz,
  renewal_count smallint not null default 0,
  scheduled_launch_at timestamptz,
  arm_authorized_at timestamptz,
  arming_at timestamptz,
  armed_at timestamptz,
  live_at timestamptz,
  schedule_missed_at timestamptz,
  released_at timestamptz,
  program_id text,
  generation_id text,
  campaign_pda text,
  mint text,
  deployment_signature text,
  reservation_version bigint not null default 1,
  authorization_nonce text,
  failure_reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ticker_reservations_chain_id_positive check (chain_id > 0),
  constraint ticker_reservations_cluster_present check (length(btrim(cluster)) between 1 and 80),
  constraint ticker_reservations_original_ticker_present check (length(btrim(original_ticker)) between 1 and 32),
  constraint ticker_reservations_normalized_ticker_valid check (normalized_ticker ~ '^[A-Z0-9]{1,12}$'),
  constraint ticker_reservations_ticker_hash_valid check (ticker_hash ~ '^[0-9a-f]{64}$'),
  constraint ticker_reservations_id_hash_valid check (reservation_id_hash ~ '^[0-9a-f]{64}$'),
  constraint ticker_reservations_status_valid check (status = any (array[
    'DRAFT_UNRESERVED',
    'SOFT_RESERVED',
    'PREPARE_MODE_RESERVED',
    'SCHEDULED_UNARMED',
    'ARM_AUTHORIZED',
    'ARMING',
    'ARMED_ONCHAIN',
    'LIVE',
    'DEPLOY_FAILED',
    'EXPIRED_GRACE',
    'RELEASED',
    'SCHEDULE_MISSED'
  ]::text[])),
  constraint ticker_reservations_renewal_count_valid check (renewal_count between 0 and 2),
  constraint ticker_reservations_version_positive check (reservation_version > 0),
  constraint ticker_reservations_grace_order check (
    expires_at is null or grace_end_at is null or grace_end_at >= expires_at
  )
);

comment on table public.ticker_reservations is
  'Canonical chain-scoped ticker reservation lifecycle. Server-only; Railway/API owns mutations.';
comment on column public.ticker_reservations.ticker_hash is
  'Lowercase hex SHA-256 of normalized_ticker. Chain-specific on-chain serializers may derive their required hash separately.';
comment on column public.ticker_reservations.reservation_version is
  'Monotonic version bound into create authorization; incremented when reservation terms change.';

create unique index if not exists ticker_reservations_blocking_ticker_uidx
  on public.ticker_reservations (chain_id, normalized_ticker)
  where status not in ('DRAFT_UNRESERVED', 'RELEASED');

create unique index if not exists ticker_reservations_blocking_draft_uidx
  on public.ticker_reservations (draft_id)
  where draft_id is not null and status not in ('DRAFT_UNRESERVED', 'RELEASED');

create unique index if not exists ticker_reservations_reservation_id_hash_uidx
  on public.ticker_reservations (reservation_id_hash);

create unique index if not exists ticker_reservations_campaign_pda_uidx
  on public.ticker_reservations (chain_id, campaign_pda)
  where campaign_pda is not null and campaign_pda <> '';

create unique index if not exists ticker_reservations_mint_uidx
  on public.ticker_reservations (chain_id, mint)
  where mint is not null and mint <> '';

create unique index if not exists ticker_reservations_deployment_signature_uidx
  on public.ticker_reservations (chain_id, deployment_signature)
  where deployment_signature is not null and deployment_signature <> '';

create index if not exists ticker_reservations_creator_history_idx
  on public.ticker_reservations (chain_id, creator_wallet, created_at desc);

create index if not exists ticker_reservations_expiry_idx
  on public.ticker_reservations (expires_at, grace_end_at)
  where status in (
    'SOFT_RESERVED',
    'PREPARE_MODE_RESERVED',
    'SCHEDULED_UNARMED',
    'DEPLOY_FAILED',
    'EXPIRED_GRACE',
    'SCHEDULE_MISSED'
  );

create index if not exists ticker_reservations_schedule_idx
  on public.ticker_reservations (scheduled_launch_at)
  where status in ('SCHEDULED_UNARMED', 'ARM_AUTHORIZED', 'ARMING', 'ARMED_ONCHAIN');

create table if not exists public.ticker_reservation_events (
  id bigint generated by default as identity primary key,
  reservation_id uuid not null references public.ticker_reservations(id) on delete cascade,
  event_type text not null,
  from_status text,
  to_status text,
  actor_type text not null default 'system',
  actor_wallet text,
  reason text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint ticker_reservation_events_event_type_present check (length(btrim(event_type)) between 1 and 80),
  constraint ticker_reservation_events_actor_type_valid check (
    actor_type = any (array['system', 'migration', 'creator', 'route_signer', 'admin', 'indexer']::text[])
  )
);

comment on table public.ticker_reservation_events is
  'Append-only audit history for canonical ticker reservation lifecycle transitions.';

create index if not exists ticker_reservation_events_reservation_idx
  on public.ticker_reservation_events (reservation_id, created_at desc);

create index if not exists ticker_reservation_events_type_idx
  on public.ticker_reservation_events (event_type, created_at desc);

alter table public.ticker_reservations enable row level security;
alter table public.ticker_reservation_events enable row level security;

revoke all on table public.ticker_reservations from public, anon, authenticated;
revoke all on table public.ticker_reservation_events from public, anon, authenticated;
revoke all on sequence public.ticker_reservation_events_id_seq from public, anon, authenticated;

grant select, insert, update, delete on table public.ticker_reservations to service_role;
grant select, insert, update, delete on table public.ticker_reservation_events to service_role;
grant usage, select on sequence public.ticker_reservation_events_id_seq to service_role;

drop trigger if exists ticker_reservations_set_updated_at on public.ticker_reservations;
create trigger ticker_reservations_set_updated_at
before update on public.ticker_reservations
for each row execute function public.set_updated_at();

with draft_source as (
  select
    gen_random_uuid() as reservation_id,
    d.id as draft_id,
    d.creator_wallet,
    d.chain_id,
    case
      when d.chain_id = 56 then 'bsc-mainnet'
      when d.chain_id = 97 then 'bsc-testnet'
      when d.chain_id in (101, 102) then 'solana-legacy-' || d.chain_id::text
      else 'chain-' || d.chain_id::text
    end as cluster,
    d.ticker as original_ticker,
    upper(left(regexp_replace(d.ticker, '[^A-Za-z0-9]', '', 'g'), 12)) as normalized_ticker,
    d.status as draft_status,
    d.visibility,
    d.created_at as draft_created_at,
    d.updated_at as draft_updated_at,
    d.deployed_at,
    d.scheduled_launch_at,
    d.campaign_address,
    d.token_address,
    d.deploy_tx_hash,
    p.published_at,
    c.factory_address
  from public.campaign_drafts d
  left join public.campaign_draft_promotion p on p.draft_id = d.id
  left join public.campaigns c
    on c.chain_id = d.chain_id
   and lower(c.campaign_address) = lower(coalesce(d.campaign_address, ''))
  where d.status <> 'archived'
),
draft_prepared as (
  select
    reservation_id,
    draft_id,
    creator_wallet,
    chain_id,
    cluster,
    original_ticker,
    normalized_ticker,
    encode(digest(normalized_ticker, 'sha256'), 'hex') as ticker_hash,
    encode(digest(reservation_id::text, 'sha256'), 'hex') as reservation_id_hash,
    case
      when campaign_address is not null and deploy_tx_hash is not null then
        case
          when scheduled_launch_at is null or scheduled_launch_at <= now() then 'LIVE'
          else 'ARMED_ONCHAIN'
        end
      when draft_status = 'scheduled' then 'SCHEDULED_UNARMED'
      when visibility = 'public' or draft_status in ('promotion_published', 'ready_to_launch') then 'PREPARE_MODE_RESERVED'
      else 'SOFT_RESERVED'
    end as reservation_status,
    coalesce(published_at, case when visibility = 'public' then draft_updated_at else null end) as effective_published_at,
    case
      when campaign_address is not null and deploy_tx_hash is not null then null
      when draft_status = 'scheduled' and scheduled_launch_at is not null then scheduled_launch_at
      when visibility = 'public' or draft_status in ('promotion_published', 'ready_to_launch') then now() + interval '14 days'
      else now() + interval '72 hours'
    end as effective_expires_at,
    scheduled_launch_at,
    deployed_at,
    campaign_address,
    token_address,
    deploy_tx_hash,
    factory_address,
    draft_status,
    visibility,
    draft_created_at,
    draft_updated_at
  from draft_source
  where normalized_ticker <> ''
),
inserted_drafts as (
  insert into public.ticker_reservations (
    id,
    draft_id,
    creator_wallet,
    chain_id,
    cluster,
    original_ticker,
    normalized_ticker,
    ticker_hash,
    reservation_id_hash,
    status,
    reserved_at,
    published_at,
    expires_at,
    grace_end_at,
    scheduled_launch_at,
    armed_at,
    live_at,
    program_id,
    campaign_pda,
    mint,
    deployment_signature,
    reservation_version,
    metadata
  )
  select
    reservation_id,
    draft_id,
    creator_wallet,
    chain_id,
    cluster,
    original_ticker,
    normalized_ticker,
    ticker_hash,
    reservation_id_hash,
    reservation_status,
    now(),
    effective_published_at,
    effective_expires_at,
    case when effective_expires_at is null then null else effective_expires_at + interval '24 hours' end,
    scheduled_launch_at,
    case when reservation_status in ('ARMED_ONCHAIN', 'LIVE') then coalesce(deployed_at, draft_updated_at) else null end,
    case when reservation_status = 'LIVE' then coalesce(scheduled_launch_at, deployed_at, draft_updated_at) else null end,
    factory_address,
    campaign_address,
    token_address,
    deploy_tx_hash,
    1,
    jsonb_build_object(
      'source', 'campaign_drafts_backfill',
      'draftStatus', draft_status,
      'visibility', visibility,
      'draftCreatedAt', draft_created_at,
      'draftUpdatedAt', draft_updated_at
    )
  from draft_prepared
  on conflict do nothing
  returning id, status, draft_id, chain_id, normalized_ticker
)
insert into public.ticker_reservation_events (
  reservation_id,
  event_type,
  from_status,
  to_status,
  actor_type,
  reason,
  metadata
)
select
  id,
  'migration_backfill_draft',
  null,
  status,
  'migration',
  'Canonical ticker reservation created from an existing active draft.',
  jsonb_build_object('draftId', draft_id, 'chainId', chain_id, 'ticker', normalized_ticker)
from inserted_drafts;

with normalized_campaigns as (
  select
    c.chain_id,
    upper(left(regexp_replace(c.symbol, '[^A-Za-z0-9]', '', 'g'), 12)) as normalized_ticker,
    c.symbol,
    c.creator_address,
    c.campaign_address,
    c.token_address,
    c.factory_address,
    coalesce(c.created_at_chain, c.created_at, now()) as effective_created_at
  from public.campaigns c
  where coalesce(c.campaign_address, '') <> ''
    and coalesce(c.symbol, '') <> ''
),
campaign_groups as (
  select
    gen_random_uuid() as reservation_id,
    chain_id,
    normalized_ticker,
    (array_agg(symbol order by effective_created_at, campaign_address))[1] as original_ticker,
    coalesce(nullif((array_agg(creator_address order by effective_created_at, campaign_address))[1], ''), 'unknown') as creator_wallet,
    (array_agg(campaign_address order by effective_created_at, campaign_address))[1] as campaign_address,
    (array_agg(token_address order by effective_created_at, campaign_address))[1] as token_address,
    (array_agg(factory_address order by effective_created_at, campaign_address))[1] as factory_address,
    min(effective_created_at) as first_live_at,
    jsonb_agg(
      jsonb_build_object(
        'campaignAddress', campaign_address,
        'tokenAddress', token_address,
        'creatorAddress', creator_address,
        'factoryAddress', factory_address,
        'createdAt', effective_created_at
      )
      order by effective_created_at, campaign_address
    ) as campaign_instances
  from normalized_campaigns
  where normalized_ticker <> ''
  group by chain_id, normalized_ticker
),
inserted_campaigns as (
  insert into public.ticker_reservations (
    id,
    draft_id,
    creator_wallet,
    chain_id,
    cluster,
    original_ticker,
    normalized_ticker,
    ticker_hash,
    reservation_id_hash,
    status,
    reserved_at,
    live_at,
    program_id,
    campaign_pda,
    mint,
    reservation_version,
    metadata
  )
  select
    g.reservation_id,
    null,
    g.creator_wallet,
    g.chain_id,
    case
      when g.chain_id = 56 then 'bsc-mainnet'
      when g.chain_id = 97 then 'bsc-testnet'
      when g.chain_id in (101, 102) then 'solana-legacy-' || g.chain_id::text
      else 'chain-' || g.chain_id::text
    end,
    g.original_ticker,
    g.normalized_ticker,
    encode(digest(g.normalized_ticker, 'sha256'), 'hex'),
    encode(digest(g.reservation_id::text, 'sha256'), 'hex'),
    'LIVE',
    g.first_live_at,
    g.first_live_at,
    g.factory_address,
    g.campaign_address,
    g.token_address,
    1,
    jsonb_build_object(
      'source', 'campaigns_backfill',
      'campaignCount', jsonb_array_length(g.campaign_instances),
      'campaigns', g.campaign_instances
    )
  from campaign_groups g
  where not exists (
    select 1
    from public.ticker_reservations r
    where r.chain_id = g.chain_id
      and r.normalized_ticker = g.normalized_ticker
      and r.status not in ('DRAFT_UNRESERVED', 'RELEASED')
  )
  on conflict do nothing
  returning id, status, chain_id, normalized_ticker, metadata
)
insert into public.ticker_reservation_events (
  reservation_id,
  event_type,
  from_status,
  to_status,
  actor_type,
  reason,
  metadata
)
select
  id,
  'migration_backfill_live_campaign',
  null,
  status,
  'migration',
  'Canonical ticker lock created from existing live campaign data.',
  jsonb_build_object(
    'chainId', chain_id,
    'ticker', normalized_ticker,
    'campaignCount', metadata -> 'campaignCount'
  )
from inserted_campaigns;
