[workspace]
members = [
  "programs/memewarzone_solana",
]
resolver = "2"

[workspace.dependencies]
anchor-lang = "0.30.1"
zeroize = "=1.3.0"
zeroize_derive = "=1.4.2"
toml = "=0.8.23"
toml_datetime = "=0.6.11"
toml_edit = "=0.22.27"
crypto-common = "=0.1.7"

[profile.release]
overflow-checks = true
