/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRewardDistributor,
  IRewardDistributorInterface,
} from "../../../contracts/CommunityRewardsVault.sol/IRewardDistributor";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "batchId",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "merkleRoot",
        type: "bytes32",
      },
      {
        internalType: "uint64",
        name: "claimDeadline",
        type: "uint64",
      },
    ],
    name: "createBatch",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IRewardDistributor__factory {
  static readonly abi = _abi;
  static createInterface(): IRewardDistributorInterface {
    return new Interface(_abi) as IRewardDistributorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRewardDistributor {
    return new Contract(address, _abi, runner) as unknown as IRewardDistributor;
  }
}
