/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface GraduationOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "graduationReached"
      | "maxPriceAge"
      | "nativeTargetForUsd"
      | "nativeUsdPrice"
      | "priceFeed"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "graduationReached",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "maxPriceAge",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nativeTargetForUsd",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nativeUsdPrice",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "priceFeed", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "graduationReached",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxPriceAge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nativeTargetForUsd",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nativeUsdPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "priceFeed", data: BytesLike): Result;
}

export interface GraduationOracle extends BaseContract {
  connect(runner?: ContractRunner | null): GraduationOracle;
  waitForDeployment(): Promise<this>;

  interface: GraduationOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  graduationReached: TypedContractMethod<
    [nativeBalance: BigNumberish, usdThreshold: BigNumberish],
    [boolean],
    "view"
  >;

  maxPriceAge: TypedContractMethod<[], [bigint], "view">;

  nativeTargetForUsd: TypedContractMethod<
    [usdAmount: BigNumberish],
    [bigint],
    "view"
  >;

  nativeUsdPrice: TypedContractMethod<[], [bigint], "view">;

  priceFeed: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "graduationReached"
  ): TypedContractMethod<
    [nativeBalance: BigNumberish, usdThreshold: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxPriceAge"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nativeTargetForUsd"
  ): TypedContractMethod<[usdAmount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "nativeUsdPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "priceFeed"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
