/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GraduationOracle } from "./GraduationOracle";
export type { IUsdPriceFeed } from "./IUsdPriceFeed";
