/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICommunityRewardsVault,
  ICommunityRewardsVaultInterface,
} from "../../../contracts/TreasuryRouter.sol/ICommunityRewardsVault";

const _abi = [
  {
    inputs: [],
    name: "depositAirdrop",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "depositSquadPool",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class ICommunityRewardsVault__factory {
  static readonly abi = _abi;
  static createInterface(): ICommunityRewardsVaultInterface {
    return new Interface(_abi) as ICommunityRewardsVaultInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICommunityRewardsVault {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ICommunityRewardsVault;
  }
}
