/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace TreasuryRouter {
  export type RouteAmountsStruct = {
    league: BigNumberish;
    recruiter: BigNumberish;
    airdrop: BigNumberish;
    squad: BigNumberish;
    protocol: BigNumberish;
  };

  export type RouteAmountsStructOutput = [
    league: bigint,
    recruiter: bigint,
    airdrop: bigint,
    squad: bigint,
    protocol: bigint
  ] & {
    league: bigint;
    recruiter: bigint;
    airdrop: bigint;
    squad: bigint;
    protocol: bigint;
  };
}

export interface TreasuryRouterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptVault"
      | "activeVault"
      | "admin"
      | "communityRewardsVault"
      | "forward"
      | "forwardingPaused"
      | "pendingSince"
      | "pendingVault"
      | "previewRoute"
      | "proposeVault"
      | "protocolRevenueVault"
      | "recruiterRewardsVault"
      | "route"
      | "setCommunityRewardsVault"
      | "setForwardingPaused"
      | "setProtocolRevenueVault"
      | "setRecruiterRewardsVault"
      | "upgradeDelay"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CommunityRewardsVaultUpdated"
      | "ForwardFailed"
      | "Forwarded"
      | "ForwardingPaused"
      | "ProtocolRevenueVaultUpdated"
      | "RecruiterRewardsVaultUpdated"
      | "RouteExecuted"
      | "VaultActivated"
      | "VaultProposed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activeVault",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "communityRewardsVault",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "forward", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "forwardingPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingSince",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "previewRoute",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposeVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolRevenueVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recruiterRewardsVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "route",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCommunityRewardsVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setForwardingPaused",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setProtocolRevenueVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRecruiterRewardsVault",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeDelay",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "communityRewardsVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "forward", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "forwardingPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingSince",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "previewRoute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposeVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "protocolRevenueVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recruiterRewardsVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "route", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setCommunityRewardsVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setForwardingPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolRevenueVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRecruiterRewardsVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeDelay",
    data: BytesLike
  ): Result;
}

export namespace CommunityRewardsVaultUpdatedEvent {
  export type InputTuple = [oldVault: AddressLike, newVault: AddressLike];
  export type OutputTuple = [oldVault: string, newVault: string];
  export interface OutputObject {
    oldVault: string;
    newVault: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ForwardFailedEvent {
  export type InputTuple = [vault: AddressLike, amount: BigNumberish];
  export type OutputTuple = [vault: string, amount: bigint];
  export interface OutputObject {
    vault: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ForwardedEvent {
  export type InputTuple = [vault: AddressLike, amount: BigNumberish];
  export type OutputTuple = [vault: string, amount: bigint];
  export interface OutputObject {
    vault: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ForwardingPausedEvent {
  export type InputTuple = [paused: boolean];
  export type OutputTuple = [paused: boolean];
  export interface OutputObject {
    paused: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtocolRevenueVaultUpdatedEvent {
  export type InputTuple = [oldVault: AddressLike, newVault: AddressLike];
  export type OutputTuple = [oldVault: string, newVault: string];
  export interface OutputObject {
    oldVault: string;
    newVault: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecruiterRewardsVaultUpdatedEvent {
  export type InputTuple = [oldVault: AddressLike, newVault: AddressLike];
  export type OutputTuple = [oldVault: string, newVault: string];
  export interface OutputObject {
    oldVault: string;
    newVault: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RouteExecutedEvent {
  export type InputTuple = [
    kind: BigNumberish,
    profile: BigNumberish,
    amountIn: BigNumberish,
    leagueAmount: BigNumberish,
    recruiterAmount: BigNumberish,
    airdropAmount: BigNumberish,
    squadAmount: BigNumberish,
    protocolAmount: BigNumberish
  ];
  export type OutputTuple = [
    kind: bigint,
    profile: bigint,
    amountIn: bigint,
    leagueAmount: bigint,
    recruiterAmount: bigint,
    airdropAmount: bigint,
    squadAmount: bigint,
    protocolAmount: bigint
  ];
  export interface OutputObject {
    kind: bigint;
    profile: bigint;
    amountIn: bigint;
    leagueAmount: bigint;
    recruiterAmount: bigint;
    airdropAmount: bigint;
    squadAmount: bigint;
    protocolAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultActivatedEvent {
  export type InputTuple = [oldVault: AddressLike, newVault: AddressLike];
  export type OutputTuple = [oldVault: string, newVault: string];
  export interface OutputObject {
    oldVault: string;
    newVault: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VaultProposedEvent {
  export type InputTuple = [newVault: AddressLike, executeAfter: BigNumberish];
  export type OutputTuple = [newVault: string, executeAfter: bigint];
  export interface OutputObject {
    newVault: string;
    executeAfter: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TreasuryRouter extends BaseContract {
  connect(runner?: ContractRunner | null): TreasuryRouter;
  waitForDeployment(): Promise<this>;

  interface: TreasuryRouterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptVault: TypedContractMethod<[], [void], "nonpayable">;

  activeVault: TypedContractMethod<[], [string], "view">;

  admin: TypedContractMethod<[], [string], "view">;

  communityRewardsVault: TypedContractMethod<[], [string], "view">;

  forward: TypedContractMethod<[], [void], "nonpayable">;

  forwardingPaused: TypedContractMethod<[], [boolean], "view">;

  pendingSince: TypedContractMethod<[], [bigint], "view">;

  pendingVault: TypedContractMethod<[], [string], "view">;

  previewRoute: TypedContractMethod<
    [amount: BigNumberish, kind: BigNumberish, profile: BigNumberish],
    [TreasuryRouter.RouteAmountsStructOutput],
    "view"
  >;

  proposeVault: TypedContractMethod<
    [newVault: AddressLike],
    [void],
    "nonpayable"
  >;

  protocolRevenueVault: TypedContractMethod<[], [string], "view">;

  recruiterRewardsVault: TypedContractMethod<[], [string], "view">;

  route: TypedContractMethod<
    [kind: BigNumberish, profile: BigNumberish],
    [TreasuryRouter.RouteAmountsStructOutput],
    "payable"
  >;

  setCommunityRewardsVault: TypedContractMethod<
    [newVault: AddressLike],
    [void],
    "nonpayable"
  >;

  setForwardingPaused: TypedContractMethod<
    [paused: boolean],
    [void],
    "nonpayable"
  >;

  setProtocolRevenueVault: TypedContractMethod<
    [newVault: AddressLike],
    [void],
    "nonpayable"
  >;

  setRecruiterRewardsVault: TypedContractMethod<
    [newVault: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeDelay: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptVault"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "activeVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "communityRewardsVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "forward"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "forwardingPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingSince"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pendingVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "previewRoute"
  ): TypedContractMethod<
    [amount: BigNumberish, kind: BigNumberish, profile: BigNumberish],
    [TreasuryRouter.RouteAmountsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "proposeVault"
  ): TypedContractMethod<[newVault: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "protocolRevenueVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recruiterRewardsVault"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "route"
  ): TypedContractMethod<
    [kind: BigNumberish, profile: BigNumberish],
    [TreasuryRouter.RouteAmountsStructOutput],
    "payable"
  >;
  getFunction(
    nameOrSignature: "setCommunityRewardsVault"
  ): TypedContractMethod<[newVault: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setForwardingPaused"
  ): TypedContractMethod<[paused: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setProtocolRevenueVault"
  ): TypedContractMethod<[newVault: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRecruiterRewardsVault"
  ): TypedContractMethod<[newVault: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeDelay"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "CommunityRewardsVaultUpdated"
  ): TypedContractEvent<
    CommunityRewardsVaultUpdatedEvent.InputTuple,
    CommunityRewardsVaultUpdatedEvent.OutputTuple,
    CommunityRewardsVaultUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ForwardFailed"
  ): TypedContractEvent<
    ForwardFailedEvent.InputTuple,
    ForwardFailedEvent.OutputTuple,
    ForwardFailedEvent.OutputObject
  >;
  getEvent(
    key: "Forwarded"
  ): TypedContractEvent<
    ForwardedEvent.InputTuple,
    ForwardedEvent.OutputTuple,
    ForwardedEvent.OutputObject
  >;
  getEvent(
    key: "ForwardingPaused"
  ): TypedContractEvent<
    ForwardingPausedEvent.InputTuple,
    ForwardingPausedEvent.OutputTuple,
    ForwardingPausedEvent.OutputObject
  >;
  getEvent(
    key: "ProtocolRevenueVaultUpdated"
  ): TypedContractEvent<
    ProtocolRevenueVaultUpdatedEvent.InputTuple,
    ProtocolRevenueVaultUpdatedEvent.OutputTuple,
    ProtocolRevenueVaultUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RecruiterRewardsVaultUpdated"
  ): TypedContractEvent<
    RecruiterRewardsVaultUpdatedEvent.InputTuple,
    RecruiterRewardsVaultUpdatedEvent.OutputTuple,
    RecruiterRewardsVaultUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RouteExecuted"
  ): TypedContractEvent<
    RouteExecutedEvent.InputTuple,
    RouteExecutedEvent.OutputTuple,
    RouteExecutedEvent.OutputObject
  >;
  getEvent(
    key: "VaultActivated"
  ): TypedContractEvent<
    VaultActivatedEvent.InputTuple,
    VaultActivatedEvent.OutputTuple,
    VaultActivatedEvent.OutputObject
  >;
  getEvent(
    key: "VaultProposed"
  ): TypedContractEvent<
    VaultProposedEvent.InputTuple,
    VaultProposedEvent.OutputTuple,
    VaultProposedEvent.OutputObject
  >;

  filters: {
    "CommunityRewardsVaultUpdated(address,address)": TypedContractEvent<
      CommunityRewardsVaultUpdatedEvent.InputTuple,
      CommunityRewardsVaultUpdatedEvent.OutputTuple,
      CommunityRewardsVaultUpdatedEvent.OutputObject
    >;
    CommunityRewardsVaultUpdated: TypedContractEvent<
      CommunityRewardsVaultUpdatedEvent.InputTuple,
      CommunityRewardsVaultUpdatedEvent.OutputTuple,
      CommunityRewardsVaultUpdatedEvent.OutputObject
    >;

    "ForwardFailed(address,uint256)": TypedContractEvent<
      ForwardFailedEvent.InputTuple,
      ForwardFailedEvent.OutputTuple,
      ForwardFailedEvent.OutputObject
    >;
    ForwardFailed: TypedContractEvent<
      ForwardFailedEvent.InputTuple,
      ForwardFailedEvent.OutputTuple,
      ForwardFailedEvent.OutputObject
    >;

    "Forwarded(address,uint256)": TypedContractEvent<
      ForwardedEvent.InputTuple,
      ForwardedEvent.OutputTuple,
      ForwardedEvent.OutputObject
    >;
    Forwarded: TypedContractEvent<
      ForwardedEvent.InputTuple,
      ForwardedEvent.OutputTuple,
      ForwardedEvent.OutputObject
    >;

    "ForwardingPaused(bool)": TypedContractEvent<
      ForwardingPausedEvent.InputTuple,
      ForwardingPausedEvent.OutputTuple,
      ForwardingPausedEvent.OutputObject
    >;
    ForwardingPaused: TypedContractEvent<
      ForwardingPausedEvent.InputTuple,
      ForwardingPausedEvent.OutputTuple,
      ForwardingPausedEvent.OutputObject
    >;

    "ProtocolRevenueVaultUpdated(address,address)": TypedContractEvent<
      ProtocolRevenueVaultUpdatedEvent.InputTuple,
      ProtocolRevenueVaultUpdatedEvent.OutputTuple,
      ProtocolRevenueVaultUpdatedEvent.OutputObject
    >;
    ProtocolRevenueVaultUpdated: TypedContractEvent<
      ProtocolRevenueVaultUpdatedEvent.InputTuple,
      ProtocolRevenueVaultUpdatedEvent.OutputTuple,
      ProtocolRevenueVaultUpdatedEvent.OutputObject
    >;

    "RecruiterRewardsVaultUpdated(address,address)": TypedContractEvent<
      RecruiterRewardsVaultUpdatedEvent.InputTuple,
      RecruiterRewardsVaultUpdatedEvent.OutputTuple,
      RecruiterRewardsVaultUpdatedEvent.OutputObject
    >;
    RecruiterRewardsVaultUpdated: TypedContractEvent<
      RecruiterRewardsVaultUpdatedEvent.InputTuple,
      RecruiterRewardsVaultUpdatedEvent.OutputTuple,
      RecruiterRewardsVaultUpdatedEvent.OutputObject
    >;

    "RouteExecuted(uint8,uint8,uint256,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      RouteExecutedEvent.InputTuple,
      RouteExecutedEvent.OutputTuple,
      RouteExecutedEvent.OutputObject
    >;
    RouteExecuted: TypedContractEvent<
      RouteExecutedEvent.InputTuple,
      RouteExecutedEvent.OutputTuple,
      RouteExecutedEvent.OutputObject
    >;

    "VaultActivated(address,address)": TypedContractEvent<
      VaultActivatedEvent.InputTuple,
      VaultActivatedEvent.OutputTuple,
      VaultActivatedEvent.OutputObject
    >;
    VaultActivated: TypedContractEvent<
      VaultActivatedEvent.InputTuple,
      VaultActivatedEvent.OutputTuple,
      VaultActivatedEvent.OutputObject
    >;

    "VaultProposed(address,uint64)": TypedContractEvent<
      VaultProposedEvent.InputTuple,
      VaultProposedEvent.OutputTuple,
      VaultProposedEvent.OutputObject
    >;
    VaultProposed: TypedContractEvent<
      VaultProposedEvent.InputTuple,
      VaultProposedEvent.OutputTuple,
      VaultProposedEvent.OutputObject
    >;
  };
}
