export type HelpCategoryId =
  | "popular"
  | "wallets"
  | "create"
  | "trading"
  | "rewards"
  | "community"
  | "recruiters"
  | "safety";

export type HelpArticle = {
  id: string;
  title: string;
  body: string;
  categories: HelpCategoryId[];
  keywords: string[];
  popular?: boolean;
};

export const HELP_CATEGORIES: { id: HelpCategoryId; label: string }[] = [
  { id: "popular", label: "Popular" },
  { id: "wallets", label: "Wallets" },
  { id: "create", label: "Create & Launch" },
  { id: "trading", label: "Trading" },
  { id: "rewards", label: "Rewards" },
  { id: "community", label: "Community" },
  { id: "recruiters", label: "Recruiters & Squads" },
  { id: "safety", label: "Safety" },
];

export const HELP_ARTICLES: HelpArticle[] = [
  {
    id: "what-is-memewarzone",
    title: "What is MemeWarzone?",
    body: "MemeWarzone is a multichain memecoin launchpad. Creators prepare, launch and promote tokens. Traders discover and trade them before and after graduation.",
    categories: ["community"],
    keywords: ["memewarzone", "what is", "launchpad", "about"],
  },
  {
    id: "which-chains",
    title: "Which chains does MemeWarzone support?",
    body: "BNB Chain and Solana. Wallets, campaigns, trading and rewards stay chain-aware.",
    categories: ["wallets", "create"],
    keywords: ["bnb", "solana", "chain", "network", "multichain"],
  },
  {
    id: "need-account",
    title: "Do I need an account?",
    body: "Your connected wallet is your identity. You can also add a public profile with username, avatar and bio.",
    categories: ["wallets", "community"],
    keywords: ["account", "signup", "login", "profile", "identity"],
  },
  {
    id: "browse-without-wallet",
    title: "Can I browse without connecting a wallet?",
    body: "Yes for public pages. Trading, following, launching, posting and claiming need a connected wallet.",
    categories: ["wallets"],
    keywords: ["browse", "guest", "connect", "without wallet"],
  },
  {
    id: "wallets",
    title: "Which wallets can I use?",
    body: "BNB/EVM: MetaMask, Rabby, Coinbase Wallet, Trust Wallet, OKX and other injected wallets. Solana: Phantom, Solflare and Backpack.",
    categories: ["wallets"],
    keywords: ["wallet", "metamask", "rabby", "phantom", "solflare", "backpack", "okx", "trust", "coinbase", "connect"],
    popular: true,
  },
  {
    id: "both-wallets",
    title: "Can I connect both a BNB wallet and a Solana wallet?",
    body: "Yes, from the same wallet selector. Features and balances stay on their own chain.",
    categories: ["wallets"],
    keywords: ["both wallets", "evm and solana", "two wallets"],
  },
  {
    id: "switch-networks",
    title: "Why am I being asked to switch networks?",
    body: "The action you started is on a different EVM network than the one selected in your wallet.",
    categories: ["wallets"],
    keywords: ["switch network", "wrong network", "chain mismatch"],
  },
  {
    id: "solana-wallet-bnb-data",
    title: "Does connecting a Solana wallet change BNB campaign data?",
    body: "No. Campaign data belongs to the campaign's chain, not whichever wallet you last connected.",
    categories: ["wallets"],
    keywords: ["sol wallet", "bnb data", "cross chain", "wrong chain"],
  },
  {
    id: "balances-combined",
    title: "Are my BNB and SOL balances combined?",
    body: "No. Native balances and chain-specific rewards stay separate.",
    categories: ["wallets", "rewards"],
    keywords: ["balance", "bnb sol combined", "separate balances"],
  },
  {
    id: "create-token",
    title: "How do I create a token?",
    body: "Open Create. Fill name, image, ticker, description, socials and graduation settings, then save a draft or deploy after wallet confirmation.",
    categories: ["create"],
    keywords: ["create", "launch", "deploy", "new token", "make a coin"],
    popular: true,
  },
  {
    id: "draft-vs-deploy",
    title: "What is the difference between Draft Mode and Direct Deploy?",
    body: "Draft Mode opens a Prepare Mode campaign without deploying a token. Direct Deploy creates the live on-chain campaign immediately after you confirm.",
    categories: ["create"],
    keywords: ["draft", "direct deploy", "difference", "prepare vs create"],
    popular: true,
  },
  {
    id: "draft-gas",
    title: "Does creating a draft cost gas?",
    body: "No. Drafts use wallet authorization. You pay gas when you deploy or schedule the live campaign.",
    categories: ["create"],
    keywords: ["draft gas", "free draft", "no gas"],
  },
  {
    id: "ticker",
    title: "Can someone else use my ticker?",
    body: "Create checks ticker availability. The final ticker depends on reservation and whether the campaign is deployed.",
    categories: ["create"],
    keywords: ["ticker", "symbol", "taken", "reserved"],
  },
  {
    id: "launch-blocked",
    title: "Why can't I launch another token?",
    body: "Creator safety can block a launch because of cooldown, a live-token limit, or eligibility rules. The Create screen shows the active restriction.",
    categories: ["create", "safety"],
    keywords: ["cannot create", "can't create", "blocked", "cooldown", "creator limit", "live token limit", "launch blocked", "deploy"],
    popular: true,
  },
  {
    id: "launch-both-chains",
    title: "Can I launch on both BNB and Solana?",
    body: "Yes. Creation is chain-aware. Each campaign lives on one chain.",
    categories: ["create"],
    keywords: ["launch both", "solana create", "bnb create"],
  },
  {
    id: "creator-initial-buy",
    title: "Can I make an initial creator buy when I deploy?",
    body: "Creator buying follows the active launch safety rules, not an unrestricted first purchase. The UI shows the restrictions for that campaign.",
    categories: ["create", "trading", "safety"],
    keywords: ["creator buy", "initial buy", "dev buy"],
  },
  {
    id: "prepare-mode",
    title: "What is Prepare Mode?",
    body: "Prepare Mode lets you build and promote a project before the token is deployed. You can grow followers, add socials, talk with the community and launch later.",
    categories: ["create"],
    keywords: ["prepare", "draft page", "promotion", "prelaunch"],
    popular: true,
  },
  {
    id: "follow-before-exists",
    title: "Can people follow a token before it exists?",
    body: "Yes. Users can follow Prepare Mode campaigns.",
    categories: ["create", "community"],
    keywords: ["follow draft", "follow prepare"],
  },
  {
    id: "arm-notification",
    title: "What does Arm Notification do?",
    body: "Followers of a Prepare Mode project can arm launch alerts so they are notified when it goes live.",
    categories: ["create", "community"],
    keywords: ["arm", "notification", "launch alert"],
  },
  {
    id: "edit-prepare",
    title: "Can I edit my Prepare Mode page?",
    body: "Yes. Creators can edit campaign information and promotional content until the launch rules lock the committed fields.",
    categories: ["create"],
    keywords: ["edit draft", "edit prepare"],
  },
  {
    id: "hide-draft",
    title: "Can I hide or archive a draft?",
    body: "Yes. Draft visibility and archival are supported from the creator tools.",
    categories: ["create"],
    keywords: ["hide draft", "archive", "unpublish"],
  },
  {
    id: "prepare-comments",
    title: "Can people comment on Prepare Mode campaigns?",
    body: "Yes. Prepare Mode has transmissions, reactions and creator replies.",
    categories: ["create", "community"],
    keywords: ["prepare comments", "transmissions", "bunker"],
  },
  {
    id: "share-prepare",
    title: "Can I share my Prepare Mode page?",
    body: "Yes. Share the page directly, including to X. The platform can generate a branded Prepare Mode share card.",
    categories: ["create"],
    keywords: ["share", "share card", "twitter", "x"],
  },
  {
    id: "schedule-launch",
    title: "Can I schedule my token launch?",
    body: "Yes. A prepared campaign can launch now or at a future time.",
    categories: ["create"],
    keywords: ["schedule", "timed launch", "countdown"],
  },
  {
    id: "what-happens-schedule",
    title: "What happens when I schedule a launch?",
    body: "You choose launch settings and time, complete deployment, and trading stays closed until that time.",
    categories: ["create"],
    keywords: ["scheduled launch", "trading closed"],
  },
  {
    id: "press-launch-again",
    title: "Do I need to come back and press Launch again?",
    body: "No. Timed launches are built to open automatically when the scheduled time is reached.",
    categories: ["create"],
    keywords: ["auto launch", "push live", "come back"],
  },
  {
    id: "change-launch-time",
    title: "Can I change the launch time after deploy?",
    body: "Once launch settings are committed on-chain, they cannot simply be changed from the frontend.",
    categories: ["create"],
    keywords: ["change time", "reschedule", "immutable"],
  },
  {
    id: "launch-timezone",
    title: "Which timezone does the launch page use?",
    body: "The scheduler shows the selected launch time in your local timezone.",
    categories: ["create"],
    keywords: ["timezone", "utc", "local time"],
  },
  {
    id: "buy-sell",
    title: "How do I buy or sell?",
    body: "Tokens still on the bonding curve buy and sell directly on MemeWarzone from Token Details or an expanded War Trade Room row.",
    categories: ["trading"],
    keywords: ["buy", "sell", "trade", "swap"],
    popular: true,
  },
  {
    id: "quote-before-trade",
    title: "Do I see a quote before trading?",
    body: "Yes. The trade panel shows expected output and the relevant trade facts before you sign.",
    categories: ["trading"],
    keywords: ["quote", "preview", "expected output"],
  },
  {
    id: "slippage",
    title: "What is slippage?",
    body: "Slippage is the price movement you are willing to accept between quote and execution.",
    categories: ["trading"],
    keywords: ["slippage", "price impact"],
  },
  {
    id: "trade-failed",
    title: "Why did my trade fail?",
    body: "Common causes: insufficient wallet or token balance, slippage, campaign trading restrictions, creator buy rules, wallet/network mismatch, or a safety/pause state. The trade UI shows the actual error.",
    categories: ["trading"],
    keywords: ["trade failed", "transaction failed", "revert", "stuck"],
  },
  {
    id: "creators-trade-own",
    title: "Can creators trade their own coin?",
    body: "Creator trading can have buy locks and buy caps. Those restrictions are shown in the trading UI.",
    categories: ["trading", "safety"],
    keywords: ["creator trade", "dev sell", "buy lock"],
  },
  {
    id: "war-trade-room",
    title: "What is the War Trade Room?",
    body: "The War Trade Room is the all-in-one market terminal. Discover, analyse and trade campaigns from one screen.",
    categories: ["trading"],
    keywords: ["war room", "war trade room", "terminal"],
  },
  {
    id: "trade-without-details",
    title: "Can I trade without opening Token Details?",
    body: "Yes. Expand a campaign row in the War Trade Room and trade there.",
    categories: ["trading"],
    keywords: ["trade from war room", "expand row"],
  },
  {
    id: "war-room-search",
    title: "What can I search for in the War Trade Room?",
    body: "Coin name, ticker, creator, token address and campaign address.",
    categories: ["trading"],
    keywords: ["search war room", "find token"],
  },
  {
    id: "war-room-both-chains",
    title: "Can I see both BNB and Solana projects in the War Trade Room?",
    body: "Yes. Feeds are chain-aware for BNB and Solana.",
    categories: ["trading"],
    keywords: ["war room solana", "war room bnb"],
  },
  {
    id: "war-room-prepare",
    title: "Does the War Trade Room include Prepare Mode projects?",
    body: "Yes. Draft and upcoming campaigns can appear there.",
    categories: ["trading", "create"],
    keywords: ["war room drafts", "upcoming"],
  },
  {
    id: "graduation",
    title: "What happens when a token graduates?",
    body: "Graduation moves the token from the bonding curve into DEX liquidity. The MemeWarzone page, chart and trade panel stay. Only the liquidity venue changes.",
    categories: ["trading"],
    keywords: ["graduate", "graduation", "dex", "bonding complete", "100%"],
    popular: true,
  },
  {
    id: "leave-after-grad",
    title: "Do I have to leave MemeWarzone after graduation?",
    body: "No. Graduation changes the liquidity venue, not the product. You keep the same project page, chart and trading interface.",
    categories: ["trading"],
    keywords: ["leave", "after graduation", "still trade here"],
    popular: true,
  },
  {
    id: "bnb-after-grad",
    title: "Where do BNB tokens trade after graduation?",
    body: "Graduated BNB campaigns use the supported Topaz DEX route through MemeWarzone.",
    categories: ["trading"],
    keywords: ["topaz", "bnb dex", "graduated bnb"],
  },
  {
    id: "solana-after-grad",
    title: "Where do Solana tokens trade after graduation?",
    body: "Graduated Solana campaigns use Meteora through the MemeWarzone interface.",
    categories: ["trading"],
    keywords: ["meteora", "solana dex", "graduated sol"],
  },
  {
    id: "chart-reset",
    title: "Does my chart reset at graduation?",
    body: "No. Market history is designed to continue across bonding and post-graduation DEX trading.",
    categories: ["trading"],
    keywords: ["chart reset", "history", "candles"],
  },
  {
    id: "external-dex-trades",
    title: "Do external DEX trades appear on MemeWarzone?",
    body: "Post-graduation market history is built to include DEX activity, not only trades started from the MemeWarzone UI.",
    categories: ["trading"],
    keywords: ["external trades", "dex prints"],
  },
  {
    id: "upvotes",
    title: "What are UpVotes?",
    body: "UpVotes are paid discovery. They support a campaign's visibility. They are not a token purchase. Cost is $3, paid in the campaign's native currency (BNB or SOL).",
    categories: ["trading"],
    keywords: ["upvote", "vote", "boost", "crowd favorite", "3 dollar", "$3"],
    popular: true,
  },
  {
    id: "upvote-not-buy",
    title: "Does buying an UpVote buy the token?",
    body: "No. An UpVote promotes the campaign. It does not buy the token.",
    categories: ["trading"],
    keywords: ["upvote buy token"],
  },
  {
    id: "upvote-rankings",
    title: "Do UpVotes influence rankings?",
    body: "Yes. They feed discovery and the Crowd Favorite competition.",
    categories: ["trading", "rewards"],
    keywords: ["upvote ranking", "crowd favorite"],
  },
  {
    id: "follow-what",
    title: "What can I follow?",
    body: "Users, live coins and Prepare Mode campaigns.",
    categories: ["community"],
    keywords: ["follow", "following"],
  },
  {
    id: "where-following",
    title: "Where can I see what I'm following?",
    body: "Command Center holds following and follower lists, with links back to those projects and profiles.",
    categories: ["community"],
    keywords: ["my following", "followers"],
  },
  {
    id: "notifications",
    title: "What notifications can I receive?",
    body: "Prepare Mode activity, launch alerts, community activity and followed-project activity.",
    categories: ["community"],
    keywords: ["notifications", "alerts", "bell"],
  },
  {
    id: "mark-read",
    title: "Can I mark notifications as read?",
    body: "Yes. Individual read state and Mark All as Read are supported.",
    categories: ["community"],
    keywords: ["mark read", "mark all"],
  },
  {
    id: "token-chat",
    title: "Does every token have a chat?",
    body: "Campaigns can have their own realtime War Room community chat on Token Details.",
    categories: ["community"],
    keywords: ["chat", "war room chat", "comments"],
  },
  {
    id: "read-chat-no-wallet",
    title: "Do I need a wallet just to read chat?",
    body: "No. Reading can work without connecting. Posting needs wallet authentication.",
    categories: ["community"],
    keywords: ["read only chat"],
  },
  {
    id: "sign-every-message",
    title: "Do I need to sign every War Room message?",
    body: "No. You sign a room session once. Messages after that do not each need a new signature.",
    categories: ["community"],
    keywords: ["sign every message", "session"],
  },
  {
    id: "comments-vs-war-room",
    title: "What is the difference between comments and War Room chat?",
    body: "Comments are persistent campaign discussion. The War Room is the realtime campaign chat.",
    categories: ["community"],
    keywords: ["comments vs chat", "transmissions"],
  },
  {
    id: "public-profile",
    title: "What can other users see on my profile?",
    body: "Depending on activity: username, avatar, bio, wallet, rank, created coins, public Prepare campaigns, public trading activity, recruiter identity, squad and public reputation.",
    categories: ["community"],
    keywords: ["public profile", "what can they see"],
  },
  {
    id: "follow-user",
    title: "Can I follow another user?",
    body: "Yes, from their public profile.",
    categories: ["community"],
    keywords: ["follow user"],
  },
  {
    id: "edit-profile",
    title: "Can I edit my profile?",
    body: "Yes. Profile settings live in Command Center → Settings.",
    categories: ["community"],
    keywords: ["edit profile", "username", "avatar", "bio"],
  },
  {
    id: "ranks",
    title: "What are MemeWarzone ranks?",
    body: "A military-style path: Recruit, Soldier, Corporal, Captain, General. Promotions can be shown and shared when you rank up.",
    categories: ["community"],
    keywords: ["rank", "recruit", "soldier", "captain", "general"],
  },
  {
    id: "command-center",
    title: "What is the Command Center?",
    body: "Your personal dashboard: portfolio, coins, drafts, recruiter, squad, airdrops, claims, followers, following, settings, notifications and Support & Safety.",
    categories: ["community"],
    keywords: ["command center", "dashboard"],
  },
  {
    id: "my-coins",
    title: "Where do I find tokens I created or my drafts?",
    body: "Command Center → My Coins holds live campaigns and drafts.",
    categories: ["create", "community"],
    keywords: ["my coins", "my drafts", "created tokens"],
  },
  {
    id: "lp-fees",
    title: "How do I claim creator LP fees?",
    body: "After graduation, open Command Center → My Coins and use the campaign's LP/DEX claim when fees are available. If the DEX pool is still indexing, wait — that is not a failed claim. If nothing is claimable, the UI says so instead of showing an error.",
    categories: ["rewards", "create"],
    keywords: ["lp fees", "harvest", "creator fees", "pool not ready"],
    popular: true,
  },
  {
    id: "leagues",
    title: "What are MemeWarzone Leagues?",
    body: "Recurring competitions: Perfect Run, Fastest Finish, Biggest Hit, Top Earner, Crowd Favorite and Recruiter League. Some run weekly and monthly; others are monthly only. League pages show prize pools and previous periods.",
    categories: ["rewards"],
    keywords: ["league", "competition", "prize pool"],
  },
  {
    id: "crowd-favorite",
    title: "What determines Crowd Favorite?",
    body: "Confirmed unique UpVotes.",
    categories: ["rewards", "trading"],
    keywords: ["crowd favorite"],
  },
  {
    id: "recruiter",
    title: "What is a MemeWarzone Recruiter?",
    body: "Recruiters bring creators, traders and communities in and build a Squad. Anyone can apply. Signup works with BNB or Solana wallets.",
    categories: ["recruiters"],
    keywords: ["recruiter", "apply", "signup"],
  },
  {
    id: "recruiter-code",
    title: "What is a recruiter code?",
    body: "Each recruiter can have a unique referral code and a shareable /r/CODE URL.",
    categories: ["recruiters"],
    keywords: ["recruiter code", "referral", "/r/"],
  },
  {
    id: "join-recruiter",
    title: "What happens when I join through a recruiter?",
    body: "Your account can be attributed to that recruiter's network/Squad under the active attribution rules.",
    categories: ["recruiters"],
    keywords: ["join recruiter", "attribution"],
  },
  {
    id: "recruiter-bnb-sol",
    title: "Can recruiters earn both BNB and SOL?",
    body: "Yes. Recruiter identity is multichain. Earnings stay native to the chain that generated them and are claimed separately.",
    categories: ["recruiters", "rewards"],
    keywords: ["recruiter sol", "recruiter bnb", "payout"],
  },
  {
    id: "squad",
    title: "What is a Squad?",
    body: "A Squad is the community around a recruiter. Users linked to that recruiter can join it and, if eligible, share the Squad Pool.",
    categories: ["recruiters"],
    keywords: ["squad", "squad pool"],
  },
  {
    id: "squad-rank",
    title: "Can I see my Squad rank and estimated reward?",
    body: "Yes. Public Squad rankings, member rank and an estimated weekly Squad reward are available when you are eligible.",
    categories: ["recruiters"],
    keywords: ["squad rank", "estimated reward"],
  },
  {
    id: "squad-not-eligible",
    title: "Why am I not eligible for Squad rewards?",
    body: "The Squad screen shows your eligibility. Qualifying activity and anti-abuse rules apply — membership alone is not enough.",
    categories: ["recruiters", "safety"],
    keywords: ["not eligible", "squad eligibility"],
  },
  {
    id: "airdrops",
    title: "What are Warzone Airdrops?",
    body: "Weekly rewards for eligible creators and traders in separate buckets. Your Airdrop area shows eligibility, why you missed, pool info and previous winners.",
    categories: ["rewards"],
    keywords: ["airdrop", "warzone airdrop", "weekly"],
  },
  {
    id: "rewards",
    title: "Where can I see and claim my rewards?",
    body: "Command Center → Claims. Categories include League, Airdrop, Recruiter, Squad and other campaign/manual rewards. BNB stays BNB. SOL stays SOL.",
    categories: ["rewards"],
    keywords: ["claim", "rewards", "claim center", "solana claim"],
    popular: true,
  },
  {
    id: "reward-statuses",
    title: "What do Pending, Claimable, Failed and Expired mean?",
    body: "Pending: exists but not claimable yet. Claimable: ready. Failed: a previous attempt did not finish — retry where offered. Expired: the claim window closed.",
    categories: ["rewards"],
    keywords: ["pending", "claimable", "failed claim", "expired"],
  },
  {
    id: "crypticpump",
    title: "What is the CrypticPump button?",
    body: "Creators can send a BNB or Solana project to CrypticPump's listing flow from Token Details. After listing, the button can become a Listed badge. That does not give CrypticPump control of the token.",
    categories: ["create"],
    keywords: ["crypticpump", "listing", "badge"],
  },
  {
    id: "help-or-abuse",
    title: "Where do I get help or report abuse?",
    body: "Search this Help Center first. Wallet, trade, create and reward questions go to Discord support. Impersonation, stolen images, fake official profiles and phishing go to Report Abuse in Command Center. Abuse replies stay in My Abuse Reports. Email is only a ping.",
    categories: ["safety"],
    keywords: ["help", "support", "discord", "report abuse", "ticket"],
    popular: true,
  },
  {
    id: "what-is-abuse",
    title: "What should I use Report Abuse for?",
    body: "Someone impersonating you, using your images without permission, fake projects or profiles, phishing with your identity, or similar identity/content abuse.",
    categories: ["safety"],
    keywords: ["impersonation", "stolen", "fake project", "phishing"],
  },
  {
    id: "failed-tx-not-abuse",
    title: "Should I report a failed transaction as abuse?",
    body: "No. Trading, wallet, reward and product issues belong in Discord support.",
    categories: ["safety", "trading"],
    keywords: ["failed transaction abuse", "not abuse"],
  },
  {
    id: "abuse-evidence",
    title: "Can I attach evidence to an Abuse Report?",
    body: "Yes. JPG, PNG, WEBP or PDF. You can add more later in the case conversation.",
    categories: ["safety"],
    keywords: ["evidence", "screenshot", "pdf"],
  },
  {
    id: "abuse-reply-email",
    title: "How will I know when Abuse replies? Can I email back?",
    body: "You get an email ping and the reply appears in Command Center → Support & Safety → My Abuse Reports. Do not reply to the email. The conversation stays on station.",
    categories: ["safety"],
    keywords: ["abuse email", "reply email", "case number"],
  },
  {
    id: "who-sees-abuse",
    title: "Who can see my Abuse Report?",
    body: "Only you and authorized Abuse Department staff. Regular Discord support cannot see Abuse Reports.",
    categories: ["safety"],
    keywords: ["who can see", "private", "abuse department"],
  },
];

export const DISCORD_SUPPORT_URL = "https://discord.gg/aXTkn3Asu";

export function searchHelpArticles(query: string, category: HelpCategoryId = "popular"): HelpArticle[] {
  const needle = String(query || "").trim().toLowerCase();
  if (needle) {
    return HELP_ARTICLES.filter((article) => {
      const haystack = [article.title, article.body, ...article.keywords].join(" ").toLowerCase();
      return haystack.includes(needle);
    });
  }
  if (category === "popular") return HELP_ARTICLES.filter((article) => article.popular);
  return HELP_ARTICLES.filter((article) => article.categories.includes(category));
}
